import { describe, it, expect } from 'vitest';
import { splitReply, openingSuggestions } from '../suggestions';
import type { Activity, Plan, TodoItem } from '../../../db';

const act = (name: string, time: string): Activity => ({
  id: name, name, time, locationName: '', notes: '', pinnedToTodo: false,
});

const plan = (days: Activity[][]): Plan => ({
  id: 'p1', name: 'Calgary', destination: 'Calgary', country: 'Canada',
  startDate: '2025-08-01', endDate: '2025-08-03',
  createdAt: '', updatedAt: '', deleted: false,
  itinerary: days.map((activities, dayIndex) => ({
    dayIndex, label: `Day ${dayIndex + 1}`, activities,
  })),
});

const todo = (over: Partial<TodoItem> = {}): TodoItem => ({
  id: 't1', planId: 'p1', title: 'Book flights', category: 'Booking',
  status: 'todo', autoGenerated: false, createdAt: '', updatedAt: '', ...over,
});

/*
 * The marker is the assistant's, and must never be the traveller's problem: a
 * model that writes it badly cannot be allowed to leave brackets sitting in
 * the middle of a sentence.
 */
describe('splitting follow-ups off a reply', () => {
  it('takes the suggestions out of the text', () => {
    const { text, suggestions } = splitReply(
      "I've added three stops to day 1.\n[[suggest: Add lunch on day 1 | Plan day 2]]",
    );
    expect(text).toBe("I've added three stops to day 1.");
    expect(suggestions).toEqual(['Add lunch on day 1', 'Plan day 2']);
  });

  it('leaves a reply that offered none alone', () => {
    const { text, suggestions } = splitReply('Day 2 is already full.');
    expect(text).toBe('Day 2 is already full.');
    expect(suggestions).toEqual([]);
  });

  it('takes no more than three', () => {
    const { suggestions } = splitReply('Done. [[suggest: a | b | c | d | e]]');
    expect(suggestions).toEqual(['a', 'b', 'c']);
  });

  // They are tapped, not read. A sentence in a pill is a sentence nobody taps.
  it('drops one too long to be a pill', () => {
    const long = 'Would you like me to consider rearranging the whole of day two for you';
    const { suggestions } = splitReply(`Done. [[suggest: Add lunch | ${long}]]`);
    expect(suggestions).toEqual(['Add lunch']);
  });

  it('ignores empty slots between separators', () => {
    const { suggestions } = splitReply('Done. [[suggest: Add lunch | |  | Plan day 2]]');
    expect(suggestions).toEqual(['Add lunch', 'Plan day 2']);
  });

  it('shows nothing rather than an empty marker', () => {
    const { text, suggestions } = splitReply('Done. [[suggest:]]');
    expect(text).toBe('Done.');
    expect(suggestions).toEqual([]);
  });
});

/*
 * An empty composer asks the traveller to invent the request, and "what can
 * this thing do" is a worse first question than any of the answers.
 */
describe('what to offer before anything has been asked', () => {
  const anyDate = new Date(2025, 6, 1);

  // The Calgary case: an arrival at 09:00 and nothing until 19:00.
  it('notices a day with a part of it skipped', () => {
    const withGap = plan([[act('Arrival', 'morning'), act('Stephen Avenue', 'evening')]]);
    expect(openingSuggestions(withGap, [], anyDate)).toContain('Fill the gap on day 1');
  });

  it('says nothing about a day that simply runs on', () => {
    const packed = plan([[act('Market', 'morning'), act('Lunch', 'noon'), act('Bar', 'evening')]]);
    expect(openingSuggestions(packed, [], anyDate)).not.toContain('Fill the gap on day 1');
  });

  it('offers to plan a day with nothing on it', () => {
    expect(openingSuggestions(plan([[act('Market', 'morning')], []]), [], anyDate))
      .toContain('Plan day 2');
  });

  it('mentions what is still open, and not what is done', () => {
    const one = plan([[act('Market', 'morning')]]);
    expect(openingSuggestions(one, [todo()], anyDate)).toContain('What still needs booking?');
    expect(openingSuggestions(one, [todo({ status: 'done' })], anyDate))
      .not.toContain('What still needs booking?');
  });

  // A wall of pills is a menu, and a menu is the problem an empty composer
  // already has.
  it('offers no more than three', () => {
    const busy = plan([
      [act('Arrival', 'morning'), act('Dinner', 'evening')],
      [],
      [],
    ]);
    expect(openingSuggestions(busy, [todo()], anyDate)).toHaveLength(3);
  });

  it('always has something to say about a plan with days', () => {
    expect(openingSuggestions(plan([[act('Market', 'morning')]]), [], anyDate).length)
      .toBeGreaterThan(0);
  });

  it('stays quiet when there is no itinerary to talk about', () => {
    expect(openingSuggestions(undefined, [], anyDate)).toEqual([]);
    expect(openingSuggestions(plan([]), [], anyDate)).toEqual([]);
  });
});
