import { v4 as uuidv4 } from 'uuid';
import { db, type Plan, type Activity } from '../db';

/**
 * Editing an activity from more than one place.
 *
 * The itinerary is not the only surface that owns a card any more — tapping a
 * pin on the map opens the same card, with the same actions. These are the
 * writes both go through, so the two cannot drift apart.
 */

type Itinerary = Plan['itinerary'];

export function patchActivity(
  itinerary: Itinerary,
  dayIndex: number,
  id: string,
  patch: Partial<Activity>,
): Itinerary {
  return itinerary.map((d, i) =>
    i === dayIndex
      ? { ...d, activities: d.activities.map((a) => (a.id === id ? { ...a, ...patch } : a)) }
      : d,
  );
}

export function removeActivity(itinerary: Itinerary, dayIndex: number, id: string): Itinerary {
  return itinerary.map((d, i) =>
    i === dayIndex ? { ...d, activities: d.activities.filter((a) => a.id !== id) } : d,
  );
}

export function saveItinerary(planId: string, itinerary: Itinerary): Promise<number> {
  return db.plans.update(planId, { itinerary, updatedAt: new Date().toISOString() });
}

/**
 * Pin an activity to the to-do list, or take it off again.
 *
 * Unpinning destroys to-dos the user may have written against, so the caller
 * supplies the confirmation — the map asks in its own way, and a caller with
 * nothing to lose can skip it. Returns null when the user backs out.
 */
export async function togglePinnedTodo(
  plan: Plan,
  dayIndex: number,
  act: Activity,
  confirmUnpin: (count: number) => boolean = () => true,
): Promise<{ pinned: boolean } | null> {
  if (act.pinnedToTodo) {
    const items = await db.todos.where('sourceActivityId').equals(act.id).toArray();
    if (items.length && !confirmUnpin(items.length)) return null;
    await db.todos.bulkDelete(items.map((t) => t.id));
    await saveItinerary(plan.id, patchActivity(plan.itinerary, dayIndex, act.id, { pinnedToTodo: false }));
    return { pinned: false };
  }

  const now = new Date().toISOString();
  await db.todos.add({
    id: uuidv4(),
    planId: plan.id,
    title: act.name,
    category: 'Other',
    status: 'todo',
    autoGenerated: false,
    sourceActivityId: act.id,
    sourceDayIndex: dayIndex,
    createdAt: now,
    updatedAt: now,
  });
  await saveItinerary(plan.id, patchActivity(plan.itinerary, dayIndex, act.id, { pinnedToTodo: true }));
  return { pinned: true };
}
