import { describe, it, expect, vi, beforeEach } from 'vitest';
import { autoGenerateTodos } from '../generateTodos';
import { db } from '../../../db';
import type { Plan, TodoItem } from '../../../db';

const basePlan: Plan = {
  id: 'plan-1',
  name: 'Tokyo',
  destination: 'Tokyo',
  country: 'Japan',
  startDate: '2025-07-14',
  endDate: '2025-07-20',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  deleted: false,
  itinerary: [],
  intake: {
    numTravellers: 2,
    kids: false,
    kidAges: null,
    likes: [],
    dislikes: [],
    budgetRange: 'mid',
    flightsBooked: false,
    accommodationBooked: false,
    needsVisa: true,
  },
};

function makeWhereChain(existing: Partial<TodoItem>[] = []) {
  return {
    equals: vi.fn().mockReturnThis(),
    toArray: vi.fn().mockResolvedValue(existing),
    sortBy: vi.fn().mockResolvedValue(existing),
  };
}

/** Helper: get the first bulkAdd call's items as a typed array */
function getBulkAdded(): Array<{ title: string; category: string; autoGenerated: boolean }> {
  const calls = vi.mocked(db.todos.bulkAdd).mock.calls;
  if (calls.length === 0) return [];
  return calls[0][0] as unknown as Array<{ title: string; category: string; autoGenerated: boolean }>;
}

describe('autoGenerateTodos', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(db.todos.where).mockReturnValue(makeWhereChain() as never);
    // bulkAdd returns a lastKey (string)
    vi.mocked(db.todos.bulkAdd).mockResolvedValue('last-key' as never);
  });

  // ── AC: flights task when not booked ──────────────────────────────────────
  it('names the travel task without assuming a flight', async () => {
    await autoGenerateTodos(basePlan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          title: 'Book travel to Tokyo',
          category: 'Booking',
          autoGenerated: true,
        }),
      ]),
    );
  });

  // ── AC: accommodation task when not booked ────────────────────────────────
  it('creates accommodation task when accommodation not booked', async () => {
    await autoGenerateTodos(basePlan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          title: 'Book accommodation for each night',
          category: 'Booking',
          autoGenerated: true,
        }),
      ]),
    );
  });

  // ── AC: visa task follows the intake answer, scoped to the country ───────
  it('creates a country-scoped visa task when the user said they need one', async () => {
    await autoGenerateTodos(basePlan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          title: 'Apply for visa to Japan',
          category: 'Document',
          autoGenerated: true,
        }),
      ]),
    );
  });

  it('creates the visa task even when flights and accommodation are booked', async () => {
    const plan: Plan = {
      ...basePlan,
      intake: {
        ...basePlan.intake!,
        flightsBooked: true,
        accommodationBooked: true,
      },
    };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Apply for visa to Japan', category: 'Document' }),
      ]),
    );
  });

  // ── AC: child entry requirements task when kids present ───────────────────
  it('creates child entry requirements task when kids = true', async () => {
    const plan: Plan = {
      ...basePlan,
      intake: { ...basePlan.intake!, kids: true },
    };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          title: 'Check child entry requirements for Japan',
          category: 'Document',
          autoGenerated: true,
        }),
      ]),
    );
  });

  // ── Edge case: flights already booked → no flights task ───────────────────
  it('does NOT create flights task if flights already booked', async () => {
    const plan: Plan = {
      ...basePlan,
      intake: { ...basePlan.intake!, flightsBooked: true },
    };
    await autoGenerateTodos(plan);
    const added = getBulkAdded();
    expect(added.some((t) => t.title.includes('flights'))).toBe(false);
  });

  // ── Edge case: deduplication — regeneration does not create duplicates ────
  it('does not duplicate tasks that already exist when itinerary is regenerated', async () => {
    const existingTodos: Partial<TodoItem>[] = [
      {
        id: 'e1',
        planId: 'plan-1',
        title: 'Book travel to Tokyo',
        category: 'Booking',
        status: 'todo',
        autoGenerated: true,
        createdAt: '',
        updatedAt: '',
      },
      {
        id: 'e2',
        planId: 'plan-1',
        title: 'Book accommodation for each night',
        category: 'Booking',
        status: 'todo',
        autoGenerated: true,
        createdAt: '',
        updatedAt: '',
      },
      {
        id: 'e3',
        planId: 'plan-1',
        title: 'Apply for visa to Japan',
        category: 'Document',
        status: 'todo',
        autoGenerated: true,
        createdAt: '',
        updatedAt: '',
      },
    ];
    vi.mocked(db.todos.where).mockReturnValue(makeWhereChain(existingTodos) as never);

    await autoGenerateTodos(basePlan);

    // All three already exist — nothing new to add (bulkAdd may not be called at all)
    const added = getBulkAdded();
    expect(added.some((t) => existingTodos.some((e) => e.title === t.title))).toBe(false);
  });

  // ── Edge case: partial duplication — only missing tasks added ─────────────
  it('only adds missing tasks when some already exist on regeneration', async () => {
    const existingTodos: Partial<TodoItem>[] = [
      {
        id: 'e1',
        planId: 'plan-1',
        title: 'Book travel to Tokyo',
        category: 'Booking',
        status: 'todo',
        autoGenerated: true,
        createdAt: '',
        updatedAt: '',
      },
    ];
    vi.mocked(db.todos.where).mockReturnValue(makeWhereChain(existingTodos) as never);

    await autoGenerateTodos(basePlan);

    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.not.arrayContaining([
        expect.objectContaining({ title: 'Book travel to Tokyo' }),
      ]),
    );
    // Should still add accommodation and visa
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Book accommodation for each night' }),
        expect.objectContaining({ title: 'Apply for visa to Japan' }),
      ]),
    );
  });

  // ── Edge case: tasks are marked autoGenerated: true ───────────────────────
  it('marks all auto-generated tasks with autoGenerated: true', async () => {
    await autoGenerateTodos(basePlan);
    const added = getBulkAdded();
    expect(added.length).toBeGreaterThan(0);
    expect(added.every((t) => t.autoGenerated === true)).toBe(true);
  });

  // ── Edge case: no intake → no tasks ───────────────────────────────────────
  it('does nothing when intake is missing', async () => {
    const plan: Plan = { ...basePlan, intake: undefined };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).not.toHaveBeenCalled();
  });

  // ── Edge case: kids = false → no child entry task ─────────────────────────
  it('does NOT create child entry task when kids = false', async () => {
    await autoGenerateTodos(basePlan); // basePlan has kids: false
    const added = getBulkAdded();
    expect(added.some((t) => t.title.includes('child entry'))).toBe(false);
  });

  // ── Destination vs country in task titles ──────────────────────────────────
  it('books travel to the city but applies for a visa to the country', async () => {
    const plan: Plan = { ...basePlan, destination: 'Paris', country: 'France' };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Book travel to Paris' }),
        expect.objectContaining({ title: 'Apply for visa to France' }),
      ]),
    );
  });

  // The reported bug: a Toronto trip produced "Apply for visa to Toronto".
  // Visas are a country-level rule, and the user may not need one at all.
  describe('visa is country-scoped and answer-driven', () => {
    const torontoPlan = (needsVisa: boolean | null | undefined): Plan => ({
      ...basePlan,
      destination: 'Toronto, Canada',
      country: 'Canada',
      intake: { ...basePlan.intake!, needsVisa },
    });

    it('names the country, never the city', async () => {
      await autoGenerateTodos(torontoPlan(true));
      const titles = getBulkAdded().map((t) => t.title);
      expect(titles).toContain('Apply for visa to Canada');
      expect(titles).not.toContain('Apply for visa to Toronto, Canada');
    });

    it('creates no visa task at all when the user said they need none', async () => {
      await autoGenerateTodos(torontoPlan(false));
      const titles = getBulkAdded().map((t) => t.title);
      expect(titles.some((t) => /visa/i.test(t))).toBe(false);
    });

    it('asks the user to check when they were not sure', async () => {
      await autoGenerateTodos(torontoPlan(null));
      expect(getBulkAdded().map((t) => t.title)).toContain(
        'Check visa requirements for Canada',
      );
    });

    it('defaults to a check when the question was never asked', async () => {
      await autoGenerateTodos(torontoPlan(undefined));
      expect(getBulkAdded().map((t) => t.title)).toContain(
        'Check visa requirements for Canada',
      );
    });

    it('falls back to the destination when no country was resolved', async () => {
      const plan: Plan = {
        ...basePlan,
        destination: 'Atlantis',
        country: undefined,
        intake: { ...basePlan.intake!, needsVisa: true },
      };
      await autoGenerateTodos(plan);
      expect(getBulkAdded().map((t) => t.title)).toContain('Apply for visa to Atlantis');
    });

    it('scopes child entry requirements to the country too', async () => {
      const plan: Plan = {
        ...basePlan,
        destination: 'Toronto, Canada',
        country: 'Canada',
        intake: { ...basePlan.intake!, kids: true },
      };
      await autoGenerateTodos(plan);
      expect(getBulkAdded().map((t) => t.title)).toContain(
        'Check child entry requirements for Canada',
      );
    });
  });
});
