import { describe, it, expect, vi, beforeEach } from 'vitest';
import { autoGenerateTodos } from '../generateTodos';
import { db } from '../../../db';
import type { Plan, TodoItem } from '../../../db';

const basePlan: Plan = {
  id: 'plan-1',
  name: 'Tokyo',
  destination: 'Tokyo',
  startDate: '2025-07-14',
  endDate: '2025-07-20',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  deleted: false,
  itinerary: [],
  intake: {
    numTravellers: 2,
    kids: false,
    kidAges: null,
    likes: [],
    dislikes: [],
    budgetRange: 'mid',
    flightsBooked: false,
    accommodationBooked: false,
  },
};

function makeWhereChain(existing: Partial<TodoItem>[] = []) {
  return {
    equals: vi.fn().mockReturnThis(),
    toArray: vi.fn().mockResolvedValue(existing),
    sortBy: vi.fn().mockResolvedValue(existing),
  };
}

/** Helper: get the first bulkAdd call's items as a typed array */
function getBulkAdded(): Array<{ title: string; category: string; autoGenerated: boolean }> {
  const calls = vi.mocked(db.todos.bulkAdd).mock.calls;
  if (calls.length === 0) return [];
  return calls[0][0] as unknown as Array<{ title: string; category: string; autoGenerated: boolean }>;
}

describe('autoGenerateTodos', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.mocked(db.todos.where).mockReturnValue(makeWhereChain() as never);
    // bulkAdd returns a lastKey (string)
    vi.mocked(db.todos.bulkAdd).mockResolvedValue('last-key' as never);
  });

  // ── AC: flights task when not booked ──────────────────────────────────────
  it('creates flights task when flights not booked', async () => {
    await autoGenerateTodos(basePlan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          title: 'Book flights to Tokyo',
          category: 'Booking',
          autoGenerated: true,
        }),
      ]),
    );
  });

  // ── AC: accommodation task when not booked ────────────────────────────────
  it('creates accommodation task when accommodation not booked', async () => {
    await autoGenerateTodos(basePlan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          title: 'Book accommodation for each night',
          category: 'Booking',
          autoGenerated: true,
        }),
      ]),
    );
  });

  // ── AC: visa task always created ──────────────────────────────────────────
  it('creates visa task regardless of booking status', async () => {
    await autoGenerateTodos(basePlan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          title: 'Apply for visa to Tokyo',
          category: 'Document',
          autoGenerated: true,
        }),
      ]),
    );
  });

  it('creates visa task even when flights and accommodation are already booked', async () => {
    const plan: Plan = {
      ...basePlan,
      intake: {
        ...basePlan.intake!,
        flightsBooked: true,
        accommodationBooked: true,
      },
    };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Apply for visa to Tokyo', category: 'Document' }),
      ]),
    );
  });

  // ── AC: child entry requirements task when kids present ───────────────────
  it('creates child entry requirements task when kids = true', async () => {
    const plan: Plan = {
      ...basePlan,
      intake: { ...basePlan.intake!, kids: true },
    };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          title: 'Check child entry requirements for Tokyo',
          category: 'Document',
          autoGenerated: true,
        }),
      ]),
    );
  });

  // ── Edge case: flights already booked → no flights task ───────────────────
  it('does NOT create flights task if flights already booked', async () => {
    const plan: Plan = {
      ...basePlan,
      intake: { ...basePlan.intake!, flightsBooked: true },
    };
    await autoGenerateTodos(plan);
    const added = getBulkAdded();
    expect(added.some((t) => t.title.includes('flights'))).toBe(false);
  });

  // ── Edge case: deduplication — regeneration does not create duplicates ────
  it('does not duplicate tasks that already exist when itinerary is regenerated', async () => {
    const existingTodos: Partial<TodoItem>[] = [
      {
        id: 'e1',
        planId: 'plan-1',
        title: 'Book flights to Tokyo',
        category: 'Booking',
        status: 'todo',
        autoGenerated: true,
        createdAt: '',
        updatedAt: '',
      },
      {
        id: 'e2',
        planId: 'plan-1',
        title: 'Book accommodation for each night',
        category: 'Booking',
        status: 'todo',
        autoGenerated: true,
        createdAt: '',
        updatedAt: '',
      },
      {
        id: 'e3',
        planId: 'plan-1',
        title: 'Apply for visa to Tokyo',
        category: 'Document',
        status: 'todo',
        autoGenerated: true,
        createdAt: '',
        updatedAt: '',
      },
    ];
    vi.mocked(db.todos.where).mockReturnValue(makeWhereChain(existingTodos) as never);

    await autoGenerateTodos(basePlan);

    // All three already exist — nothing new to add (bulkAdd may not be called at all)
    const added = getBulkAdded();
    expect(added.some((t) => existingTodos.some((e) => e.title === t.title))).toBe(false);
  });

  // ── Edge case: partial duplication — only missing tasks added ─────────────
  it('only adds missing tasks when some already exist on regeneration', async () => {
    const existingTodos: Partial<TodoItem>[] = [
      {
        id: 'e1',
        planId: 'plan-1',
        title: 'Book flights to Tokyo',
        category: 'Booking',
        status: 'todo',
        autoGenerated: true,
        createdAt: '',
        updatedAt: '',
      },
    ];
    vi.mocked(db.todos.where).mockReturnValue(makeWhereChain(existingTodos) as never);

    await autoGenerateTodos(basePlan);

    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.not.arrayContaining([
        expect.objectContaining({ title: 'Book flights to Tokyo' }),
      ]),
    );
    // Should still add accommodation and visa
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Book accommodation for each night' }),
        expect.objectContaining({ title: 'Apply for visa to Tokyo' }),
      ]),
    );
  });

  // ── Edge case: tasks are marked autoGenerated: true ───────────────────────
  it('marks all auto-generated tasks with autoGenerated: true', async () => {
    await autoGenerateTodos(basePlan);
    const added = getBulkAdded();
    expect(added.length).toBeGreaterThan(0);
    expect(added.every((t) => t.autoGenerated === true)).toBe(true);
  });

  // ── Edge case: no intake → no tasks ───────────────────────────────────────
  it('does nothing when intake is missing', async () => {
    const plan: Plan = { ...basePlan, intake: undefined };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).not.toHaveBeenCalled();
  });

  // ── Edge case: kids = false → no child entry task ─────────────────────────
  it('does NOT create child entry task when kids = false', async () => {
    await autoGenerateTodos(basePlan); // basePlan has kids: false
    const added = getBulkAdded();
    expect(added.some((t) => t.title.includes('child entry'))).toBe(false);
  });

  // ── Edge case: destination used in task titles ─────────────────────────────
  it('uses the plan destination in flights and visa task titles', async () => {
    const plan: Plan = { ...basePlan, destination: 'Paris' };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Book flights to Paris' }),
        expect.objectContaining({ title: 'Apply for visa to Paris' }),
      ]),
    );
  });
});
