import { describe, it, expect, vi, beforeEach } from 'vitest';
import { autoGenerateTodos } from '../generateTodos';
import { db } from '../../../db';
import type { Plan } from '../../../db';

const basePlan: Plan = {
  id: 'plan-1',
  name: 'Tokyo',
  destination: 'Tokyo',
  startDate: '2025-07-14',
  endDate: '2025-07-20',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  deleted: false,
  itinerary: [],
  intake: {
    numTravellers: 2,
    kids: false,
    kidAges: null,
    likes: [],
    dislikes: [],
    budgetRange: 'mid',
    flightsBooked: false,
    accommodationBooked: false,
  },
};

describe('autoGenerateTodos', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    // The mock setup in setup.ts already chains where().equals().toArray()
    // but we need the full chain to resolve
    const mockChain = {
      equals: vi.fn().mockReturnThis(),
      toArray: vi.fn().mockResolvedValue([]),
      sortBy: vi.fn().mockResolvedValue([]),
    };
    vi.mocked(db.todos.where).mockReturnValue(mockChain as never);
    vi.mocked(db.todos.bulkAdd).mockResolvedValue([]);
  });

  it('creates flights task when flights not booked', async () => {
    await autoGenerateTodos(basePlan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Book flights to Tokyo', category: 'Booking' }),
      ]),
    );
  });

  it('creates accommodation task when accommodation not booked', async () => {
    await autoGenerateTodos(basePlan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Book accommodation for each night', category: 'Booking' }),
      ]),
    );
  });

  it('does NOT create flights task if flights already booked', async () => {
    const plan = { ...basePlan, intake: { ...basePlan.intake!, flightsBooked: true } };
    await autoGenerateTodos(plan);
    const calls = vi.mocked(db.todos.bulkAdd).mock.calls;
    if (calls.length > 0) {
      const added = calls[0][0] as unknown as Array<{ title: string }>;
      expect(added.some((t) => t.title.includes('flights'))).toBe(false);
    }
  });

  it('creates child entry requirements task when kids = true', async () => {
    const plan = { ...basePlan, intake: { ...basePlan.intake!, kids: true } };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({ title: 'Check child entry requirements for Tokyo', category: 'Document' }),
      ]),
    );
  });

  it('does not duplicate tasks that already exist', async () => {
    const existingChain = {
      equals: vi.fn().mockReturnThis(),
      toArray: vi.fn().mockResolvedValue([
        { id: 'e1', planId: 'plan-1', title: 'Book flights to Tokyo', category: 'Booking', status: 'todo', autoGenerated: true, createdAt: '', updatedAt: '' },
      ]),
      sortBy: vi.fn().mockResolvedValue([]),
    };
    vi.mocked(db.todos.where).mockReturnValue(existingChain as never);

    await autoGenerateTodos(basePlan);
    if (vi.mocked(db.todos.bulkAdd).mock.calls.length > 0) {
      const added = vi.mocked(db.todos.bulkAdd).mock.calls[0][0] as unknown as Array<{ title: string }>;
      expect(added.every((t) => t.title !== 'Book flights to Tokyo')).toBe(true);
    }
  });

  it('does nothing when intake is missing', async () => {
    const plan = { ...basePlan, intake: undefined };
    await autoGenerateTodos(plan);
    expect(db.todos.bulkAdd).not.toHaveBeenCalled();
  });
});
