import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent } from '../../../test/render';
import { useLiveQuery } from 'dexie-react-hooks';
import TripPhasePanel from '../TripPhasePanel';
import type { Activity, Plan, TodoItem } from '../../../db';

vi.mock('dexie-react-hooks');

const act = (id: string, name: string, time: string): Activity => ({
  id, name, time, locationName: 'Shibuya', notes: '', pinnedToTodo: false,
});

const plan = (days: Activity[][]): Plan => ({
  id: 'p1', name: 'Japan', destination: 'Tokyo', country: 'Japan',
  startDate: '2025-08-01', endDate: '2025-08-05',
  createdAt: '', updatedAt: '', deleted: false,
  itinerary: days.map((activities, dayIndex) => ({
    dayIndex, label: `Day ${dayIndex + 1}`, activities,
  })),
});

const full = plan([
  [act('a', 'Fish market', 'morning')],
  [act('b', 'Temple', 'morning')],
  [act('c', 'Museum', 'morning'), act('d', 'Ramen', 'evening')],
  [act('e', 'Park', 'noon')],
  [act('f', 'Flight home', 'morning')],
]);

const todos: TodoItem[] = [];
const onGoToDay = vi.fn();

const at = (iso: string, hour = 9) => {
  vi.useFakeTimers();
  vi.setSystemTime(new Date(`${iso}T${String(hour).padStart(2, '0')}:00:00`));
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.mocked(useLiveQuery).mockReturnValue(todos);
});
afterEach(() => {
  vi.useRealTimers();
});

const show = (p: Plan = full) =>
  render(<TripPhasePanel plan={p} onGoToDay={onGoToDay} />);

/*
 * This replaced one line of text with the same shape in all three phases:
 * "Day 4 of your trip · 3 days to go". Planning a trip, being on one and
 * having been on one are three different jobs.
 */
describe('before the trip', () => {
  it('counts down and reports how much is planned', () => {
    at('2025-07-29');
    show(plan([[act('a', 'Market', 'morning')], [], []]));

    expect(screen.getByTestId('trip-phase')).toHaveAttribute('data-phase', 'upcoming');
    expect(screen.getByTestId('phase-headline')).toHaveTextContent('3 days to go');
    expect(screen.getByTestId('phase-upcoming')).toHaveTextContent('1/3');
  });

  // A readiness panel that names five problems is a fifth as likely to get any
  // of them fixed.
  it('offers one next step, and it goes where it says', () => {
    at('2025-07-29');
    show(plan([[act('a', 'Market', 'morning')], [], []]));

    const step = screen.getByTestId('phase-next-step');
    expect(step).toHaveTextContent('Day 2 has nothing on it yet');
    fireEvent.click(step);
    expect(onGoToDay).toHaveBeenCalledWith(1);
  });

  it('says so plainly when there is nothing left to do', () => {
    at('2025-07-29');
    show();
    expect(screen.getByTestId('phase-next-step')).toHaveTextContent('nothing is outstanding');
  });

  it('leads with what is overdue once every day is full', () => {
    at('2025-07-29');
    vi.mocked(useLiveQuery).mockReturnValue([
      { id: 't', planId: 'p1', title: 'Visa', category: 'Document', status: 'todo',
        dueDate: '2025-07-01', autoGenerated: false, createdAt: '', updatedAt: '' },
    ]);
    show();

    expect(screen.getByTestId('phase-next-step')).toHaveTextContent('Visa was due');
  });
});

/*
 * A day is a list read from the top, and at 6pm the top of today is this
 * morning. The during-trip case was served worst.
 */
describe('during the trip', () => {
  it('opens on today, not on day one', () => {
    at('2025-08-03');
    show();

    expect(screen.getByTestId('trip-phase')).toHaveAttribute('data-phase', 'active');
    expect(screen.getByTestId('phase-headline')).toHaveTextContent('Day 3 of 5');
  });

  it('names what is happening now rather than what happened this morning', () => {
    at('2025-08-03', 19);
    show();

    const next = screen.getByTestId('phase-up-next');
    expect(next).toHaveTextContent('Now');
    expect(next).toHaveTextContent('Ramen');
  });

  it('looks ahead when the current part of the day is empty', () => {
    at('2025-08-03', 14); // noon, and today has morning + evening only
    show();

    const next = screen.getByTestId('phase-up-next');
    expect(next).toHaveTextContent('Up next');
    expect(next).toHaveTextContent('Ramen');
  });

  it('admits when the day is over', () => {
    at('2025-08-04', 22); // day four has one noon activity, already past
    show();

    expect(screen.getByTestId('phase-up-next')).toHaveTextContent('Nothing else planned today');
  });

  it('offers tomorrow, and goes there', () => {
    at('2025-08-03');
    show();

    fireEvent.click(screen.getByTestId('phase-tomorrow'));
    expect(onGoToDay).toHaveBeenCalledWith(3);
  });
});

/* A finished trip should stop asking to be planned. */
describe('after the trip', () => {
  it('reports what happened and asks for nothing', () => {
    at('2025-08-12');
    show();

    expect(screen.getByTestId('trip-phase')).toHaveAttribute('data-phase', 'past');
    expect(screen.getByTestId('phase-headline')).toHaveTextContent('Back 7 days ago');
    expect(screen.getByTestId('phase-past')).toHaveTextContent('6');
    expect(screen.queryByTestId('phase-next-step')).not.toBeInTheDocument();
    expect(screen.queryByTestId('phase-up-next')).not.toBeInTheDocument();
  });
});

describe('when the dates say nothing', () => {
  it('stays out of the way entirely', () => {
    at('2025-08-03');
    render(
      <TripPhasePanel plan={{ ...full, startDate: '', endDate: '' }} onGoToDay={onGoToDay} />,
    );
    expect(screen.queryByTestId('trip-phase')).not.toBeInTheDocument();
  });
});
