import { describe, it, expect } from 'vitest';
import { currentSlot, readiness, todayGlance, tripRecord } from '../tripPhase';
import type { Activity, Plan, TodoItem } from '../../db';

const at = (h: number) => new Date(2025, 7, 3, h, 0, 0);

const act = (id: string, name: string, time: string, locationName = ''): Activity => ({
  id, name, time, locationName, notes: '', pinnedToTodo: false,
});

const plan = (days: Activity[][], over: Partial<Plan> = {}): Plan => ({
  id: 'p1', name: 'Japan', destination: 'Tokyo', country: 'Japan',
  startDate: '2025-08-01', endDate: `2025-08-0${days.length}`,
  createdAt: '', updatedAt: '', deleted: false,
  itinerary: days.map((activities, dayIndex) => ({
    dayIndex, label: `Day ${dayIndex + 1}`, activities,
  })),
  ...over,
});

const todo = (over: Partial<TodoItem>): TodoItem => ({
  id: 't1', planId: 'p1', title: 'Book flights', category: 'Booking',
  status: 'todo', autoGenerated: false, createdAt: '', updatedAt: '', ...over,
});

describe('what part of the day it is', () => {
  it('reads the clock into a slot', () => {
    expect(currentSlot(at(8))).toBe('morning');
    expect(currentSlot(at(14))).toBe('noon');
    expect(currentSlot(at(19))).toBe('evening');
    expect(currentSlot(at(22))).toBe('night');
  });

  // Night runs past midnight, so 2am belongs to it rather than to nothing.
  it('keeps the small hours in the night', () => {
    expect(currentSlot(at(2))).toBe('night');
  });
});

/*
 * Before departure the only question is "am I ready", and the answer has to be
 * made of things that can still be done about it.
 */
describe('how ready a trip is', () => {
  it('finds the days with nothing on them', () => {
    const r = readiness(plan([[act('a', 'Museum', 'morning')], [], []]), []);
    expect(r.emptyDays).toEqual([1, 2]);
    expect(r.firstEmptyDay).toBe(1);
  });

  /*
   * Counts empty days, not thin ones. A day with one thing on it is a decision
   * someone made; calling that unfinished is second-guessing them.
   */
  it('leaves a deliberately quiet day alone', () => {
    const r = readiness(plan([[act('a', 'Beach', 'noon')]]), []);
    expect(r.emptyDays).toEqual([]);
    expect(r.firstEmptyDay).toBeNull();
  });

  it('separates what is overdue from what is merely next', () => {
    const r = readiness(
      plan([[]]),
      [
        todo({ id: 'late', title: 'Visa', dueDate: '2025-07-01' }),
        todo({ id: 'soon', title: 'Insurance', dueDate: '2025-08-20' }),
        todo({ id: 'later', title: 'Pack', dueDate: '2025-09-01' }),
      ],
      at(9),
    );
    expect(r.overdue.map(t => t.id)).toEqual(['late']);
    expect(r.nextDue?.id).toBe('soon');
  });

  it('does not count a finished task against you', () => {
    const r = readiness(
      plan([[]]),
      [todo({ id: 'done', dueDate: '2025-07-01', status: 'done' })],
      at(9),
    );
    expect(r.overdue).toEqual([]);
    expect(r.openTodos).toBe(0);
    expect(r.doneTodos).toBe(1);
  });

  it('counts what has to happen before departure, not merely soon', () => {
    const r = readiness(
      plan([[]], { startDate: '2025-08-10' }),
      [
        todo({ id: 'before', dueDate: '2025-08-05' }),
        todo({ id: 'during', dueDate: '2025-08-12' }),
      ],
      at(9),
    );
    expect(r.dueBeforeDeparture).toBe(1);
  });
});

/*
 * A day is a list read from the top, and at 6pm the top of today is this
 * morning. That is the during-trip failure this exists to fix.
 */
describe('today, split by where the clock has got to', () => {
  const running = plan(
    [
      [],
      [],
      [
        act('m', 'Fish market', 'morning'),
        act('n', 'Lunch', 'noon'),
        act('e', 'Dinner', 'evening'),
      ],
      [act('t', 'Train', 'morning')],
    ],
    { startDate: '2025-08-01', endDate: '2025-08-04' },
  );

  it('puts the morning behind you by the evening', () => {
    const g = todayGlance(running, at(19))!;
    expect(g.done.map(a => a.id)).toEqual(['m', 'n']);
    expect(g.now.map(a => a.id)).toEqual(['e']);
    expect(g.later).toEqual([]);
  });

  it('has the whole day ahead first thing', () => {
    const g = todayGlance(running, at(7))!;
    expect(g.done).toEqual([]);
    expect(g.now.map(a => a.id)).toEqual(['m']);
    expect(g.later.map(a => a.id)).toEqual(['n', 'e']);
  });

  it('knows which day it is on and where', () => {
    const g = todayGlance(running, at(9))!;
    expect(g.dayIndex).toBe(2);
    expect(g.city).toBeTruthy();
  });

  it('offers tomorrow, and nothing on the last day', () => {
    expect(todayGlance(running, at(9))!.tomorrow?.dayIndex).toBe(3);
    const lastDay = new Date(2025, 7, 4, 9);
    expect(todayGlance(running, lastDay)!.tomorrow).toBeNull();
  });

  it('says nothing at all when the trip is not running', () => {
    expect(todayGlance(running, new Date(2025, 6, 1))).toBeNull();
    expect(todayGlance(running, new Date(2025, 8, 1))).toBeNull();
  });
});

/* A finished trip should stop asking to be planned. */
describe('what a finished trip amounts to', () => {
  it('counts what happened', () => {
    const r = tripRecord(
      plan([[act('a', 'Museum', 'morning')], [act('b', 'Park', 'noon'), act('c', 'Bar', 'night')]]),
      new Date(2025, 7, 10),
    );
    expect(r.days).toBe(2);
    expect(r.activities).toBe(3);
  });

  it('measures how long ago it ended', () => {
    const r = tripRecord(plan([[], []], { endDate: '2025-08-02' }), new Date(2025, 7, 9));
    expect(r.endedDaysAgo).toBe(7);
  });

  /*
   * Returning to a city later is a second visit, and reads as one — a
   * Montreal → Percé → Montreal road trip is three legs, not two cities.
   *
   * The arrival and departure legs are what put Montreal on the route at all;
   * a city the trip never declares is not one `cityForDay` will recognise,
   * which is right — it is how a stray mention avoids renaming a day.
   */
  it('keeps a return leg in the route', () => {
    const roadTrip = plan([[], [], []], {
      destination: 'Percé',
      country: 'Canada',
      arrival: { city: 'Montreal', country: 'Canada' },
      departure: { city: 'Montreal', country: 'Canada' },
    });
    roadTrip.itinerary[0].activities = [act('a', 'Depart', 'morning', 'Montreal')];
    roadTrip.itinerary[1].activities = [act('b', 'Rock', 'noon', 'Percé')];
    roadTrip.itinerary[2].activities = [act('c', 'Home', 'evening', 'Montreal')];

    expect(tripRecord(roadTrip).cities).toEqual(['Montreal', 'Percé', 'Montreal']);
  });
});
