import Dexie, { type Table } from 'dexie';

// ─── Entity types ──────────────────────────────────────────────────────────

/**
 * How a traveller reaches the trip, or leaves it.
 *
 * Not everything is a flight. A road trip has no ticket to book, a train
 * crosses a border without an airport, and a domestic bus needs no visa at
 * all — assuming otherwise produced to-dos that were simply wrong.
 */
export type TravelMode = 'flight' | 'train' | 'bus' | 'car' | 'ferry' | 'other';

/** One end of the trip: getting there, or getting home. */
export interface TripLeg {
  /** Where the traveller actually lands, which need not be the destination —
   *  flying into Osaka for a Kyoto trip is ordinary. */
  city?: string;
  country?: string;
  /** ISO date. May sit outside the trip's own dates for an overnight leg. */
  date?: string;
  /**
   * 'HH:MM'. One of the few things in this app that genuinely has a clock
   * time: a 22:40 arrival rules out a full first day, and the itinerary
   * should know that.
   */
  time?: string;
  mode?: TravelMode;
}

/** A further city on a multi-city trip, in the order it is visited. */
export interface TripStop {
  id: string;
  city: string;
  country?: string;
  /** Nights spent here — enough to apportion days without exact dates. */
  nights?: number;
}

export interface Plan {
  id: string;          // UUID v4
  name: string;        // Display name / destination
  destination: string;
  /**
   * Country the destination sits in, resolved when the plan is created.
   * Optional: plans created before this existed, or typed free-form with no
   * geocoding match, have none. Drives the visa to-do, which is a per-country
   * requirement — a "Toronto visa" is not a thing.
   * Not indexed, so no Dexie version bump is needed.
   */
  country?: string;
  startDate: string;   // ISO 8601 date string e.g. '2025-03-14'
  endDate: string;
  /**
   * Arrival and departure, when the user has said. Both optional: a plan is
   * useful long before the travel is worked out, and every plan created
   * before these existed has neither.
   */
  arrival?: TripLeg;
  departure?: TripLeg;
  /**
   * Cities beyond the destination, in visit order. The destination stays the
   * trip's first and primary city rather than becoming stops[0], so nothing
   * that already reads plan.destination has to change.
   */
  stops?: TripStop[];
  /**
   * Whether the trip crosses a border.
   *
   * The only honest basis for an entry-requirement to-do. It cannot be
   * inferred from the transport mode — a train can cross a border and a
   * flight can be domestic — and the app never learns where the traveller
   * lives. `null` means unsure, which asks them to check rather than assuming
   * either way.
   */
  international?: boolean | null;
  createdAt: string;   // ISO 8601 datetime
  updatedAt: string;
  deleted: boolean;    // soft-delete flag
  // Intake metadata (populated by AI intake chat)
  intake?: {
    numTravellers: number | null;
    kids: boolean | null;
    kidAges: number[] | null;
    likes: string[];
    dislikes: string[];
    budgetRange: 'budget' | 'mid' | 'premium' | 'luxury' | null;
    flightsBooked: boolean | null;
    accommodationBooked: boolean | null;
    /**
     * Whether a visa is needed for this trip. Asked about the COUNTRY, since
     * that is what visas apply to. `null` means "not sure", which produces a
     * check-the-requirements reminder rather than an apply-for-one task.
     */
    needsVisa?: boolean | null;
  };
  itinerary: Day[]; // inline — no separate table
}

export interface Day {
  dayIndex: number;  // 0-based
  label: string;     // e.g. 'Day 1 — Mon 14 Jul'
  estimatedDailySpend?: {
    min: number;
    max: number;
    currency: 'USD';
  };
  activities: Activity[];
}

export interface Activity {
  id: string;            // UUID v4
  name: string;
  time: string;          // 'HH:MM' 24h
  locationName: string;
  coordinates?: [number, number]; // [lng, lat]
  notes: string;
  pinnedToTodo: boolean;
  budgetWarning?: boolean;
}

export interface TodoItem {
  id: string;          // UUID v4
  planId: string;
  title: string;
  category: 'Booking' | 'Document' | 'Packing' | 'Other';
  status: 'todo' | 'in_progress' | 'done';
  dueDate?: string;    // ISO date string
  /**
   * Kept at the top of its category. The one or two things that actually
   * matter get lost in a list the app itself keeps adding to.
   * Not indexed, so no Dexie version bump is needed.
   */
  pinned?: boolean;
  autoGenerated: boolean;
  sourceActivityId?: string;
  sourceDayIndex?: number;
  createdAt: string;
  updatedAt: string;
}

export interface ClipboardItem {
  id: string;          // UUID v4
  planId: string;
  type: 'Note' | 'Boarding Pass' | 'Hotel' | 'Email' | 'Location' | 'Other';
  title: string;
  body?: string;
  fileBlob?: Blob;
  fileName?: string;
  fileSize?: number;   // bytes
  linkedDayIndex?: number;
  linkedActivityId?: string;
  /**
   * When this happens, for an item linked to a day — a 3pm check-in, a 06:40
   * boarding time. Stored in the same field shape as an activity's, so it is
   * either a slot id or 'HH:MM' and shows up under the right part of the day.
   */
  time?: string;
  createdAt: string;
  updatedAt: string;
}

// ─── Database class ─────────────────────────────────────────────────────────

export class AiTravelPlannerDB extends Dexie {
  plans!: Table<Plan, string>;
  todos!: Table<TodoItem, string>;
  clipboard!: Table<ClipboardItem, string>;

  constructor() {
    super('AiTravelPlannerDB');

    this.version(1).stores({
      plans:     'id, destination, deleted, createdAt',
      todos:     'id, planId, status, category, dueDate, sourceActivityId',
      clipboard: 'id, planId, type, createdAt',
    });
  }
}

export const db = new AiTravelPlannerDB();
