import Dexie, { type Table } from 'dexie';

// ─── Entity types ──────────────────────────────────────────────────────────

export interface Plan {
  id: string;          // UUID v4
  name: string;        // Display name / destination
  destination: string;
  /**
   * Country the destination sits in, resolved when the plan is created.
   * Optional: plans created before this existed, or typed free-form with no
   * geocoding match, have none. Drives the visa to-do, which is a per-country
   * requirement — a "Toronto visa" is not a thing.
   * Not indexed, so no Dexie version bump is needed.
   */
  country?: string;
  startDate: string;   // ISO 8601 date string e.g. '2025-03-14'
  endDate: string;
  createdAt: string;   // ISO 8601 datetime
  updatedAt: string;
  deleted: boolean;    // soft-delete flag
  // Intake metadata (populated by AI intake chat)
  intake?: {
    numTravellers: number | null;
    kids: boolean | null;
    kidAges: number[] | null;
    likes: string[];
    dislikes: string[];
    budgetRange: 'budget' | 'mid' | 'premium' | 'luxury' | null;
    flightsBooked: boolean | null;
    accommodationBooked: boolean | null;
  };
  itinerary: Day[]; // inline — no separate table
}

export interface Day {
  dayIndex: number;  // 0-based
  label: string;     // e.g. 'Day 1 — Mon 14 Jul'
  estimatedDailySpend?: {
    min: number;
    max: number;
    currency: 'USD';
  };
  activities: Activity[];
}

export interface Activity {
  id: string;            // UUID v4
  name: string;
  time: string;          // 'HH:MM' 24h
  locationName: string;
  coordinates?: [number, number]; // [lng, lat]
  notes: string;
  pinnedToTodo: boolean;
  budgetWarning?: boolean;
}

export interface TodoItem {
  id: string;          // UUID v4
  planId: string;
  title: string;
  category: 'Booking' | 'Document' | 'Packing' | 'Other';
  status: 'todo' | 'in_progress' | 'done';
  dueDate?: string;    // ISO date string
  autoGenerated: boolean;
  sourceActivityId?: string;
  sourceDayIndex?: number;
  createdAt: string;
  updatedAt: string;
}

export interface ClipboardItem {
  id: string;          // UUID v4
  planId: string;
  type: 'Note' | 'Boarding Pass' | 'Hotel' | 'Email' | 'Location' | 'Other';
  title: string;
  body?: string;
  fileBlob?: Blob;
  fileName?: string;
  fileSize?: number;   // bytes
  linkedDayIndex?: number;
  linkedActivityId?: string;
  createdAt: string;
  updatedAt: string;
}

// ─── Database class ─────────────────────────────────────────────────────────

export class AiTravelPlannerDB extends Dexie {
  plans!: Table<Plan, string>;
  todos!: Table<TodoItem, string>;
  clipboard!: Table<ClipboardItem, string>;

  constructor() {
    super('AiTravelPlannerDB');

    this.version(1).stores({
      plans:     'id, destination, deleted, createdAt',
      todos:     'id, planId, status, category, dueDate, sourceActivityId',
      clipboard: 'id, planId, type, createdAt',
    });
  }
}

export const db = new AiTravelPlannerDB();
