import { v4 as uuidv4 } from 'uuid';
import { db, type Plan, type TodoItem, type ClipboardItem } from './index';
import { useAppStore } from '../store';

/**
 * First-launch demo seed.
 *
 * On the very first boot (no plans in IndexedDB, no `aitp_seeded` flag) a
 * realistic 3-day Tokyo plan is written so a new user can explore every tab
 * without generating anything. The seed runs at most once — even if the user
 * later deletes all plans the `aitp_seeded` localStorage flag prevents a
 * re-seed. Entirely static data; no AI calls.
 */

export const SEEDED_FLAG = 'aitp_seeded';
export const DEMO_BANNER_DISMISSED = 'aitp_demo_banner_dismissed';

/** ISO date string N days from today (date portion only). */
function isoDateOffset(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() + days);
  return d.toISOString().slice(0, 10);
}

function activity(name: string, time: string, locationName: string, notes: string) {
  return {
    id: uuidv4(),
    name,
    time,
    locationName,
    notes,
    pinnedToTodo: false,
    budgetWarning: false,
  };
}

function buildDemoPlan(): Plan {
  const now = new Date().toISOString();
  return {
    id: uuidv4(),
    name: 'Tokyo Explorer',
    destination: 'Tokyo, Japan',
    startDate: isoDateOffset(30),
    endDate: isoDateOffset(32),
    createdAt: now,
    updatedAt: now,
    deleted: false,
    intake: {
      numTravellers: 2,
      kids: false,
      kidAges: [],
      likes: ['street food', 'temples', 'anime'],
      dislikes: ['crowds'],
      budgetRange: 'mid',
      flightsBooked: true,
      accommodationBooked: true,
    },
    itinerary: [
      {
        dayIndex: 0,
        label: 'Day 1 — Tokyo Arrival',
        estimatedDailySpend: { min: 80, max: 140, currency: 'USD' },
        activities: [
          activity('Tsukiji Outer Market', '08:00', 'Tsukiji, Tokyo', 'Arrive early for a fresh sushi breakfast.'),
          activity('Senso-ji Temple', '10:30', 'Asakusa, Tokyo', "Tokyo's oldest temple — browse Nakamise shopping street."),
          activity('Akihabara Electric Town', '14:00', 'Akihabara, Tokyo', 'Anime, electronics and retro arcades.'),
          activity('Shibuya Crossing', '19:00', 'Shibuya, Tokyo', 'Iconic scramble crossing at night.'),
        ],
      },
      {
        dayIndex: 1,
        label: 'Day 2 — Culture & Parks',
        estimatedDailySpend: { min: 70, max: 120, currency: 'USD' },
        activities: [
          activity('Meiji Shrine', '09:00', 'Shibuya, Tokyo', 'Forested shrine dedicated to Emperor Meiji.'),
          activity('Harajuku Takeshita Street', '11:00', 'Harajuku, Tokyo', 'Youth fashion and crepes.'),
          activity('Shinjuku Gyoen', '13:30', 'Shinjuku, Tokyo', 'Relaxing garden stroll.'),
          activity('Omoide Yokocho', '19:30', 'Shinjuku, Tokyo', 'Atmospheric alley of tiny yakitori bars.'),
        ],
      },
      {
        dayIndex: 2,
        label: 'Day 3 — Day Trip',
        estimatedDailySpend: { min: 90, max: 160, currency: 'USD' },
        activities: [
          activity('Nikko Tosho-gu Shrine', '09:00', 'Nikko, Japan', 'Ornate UNESCO World Heritage shrine.'),
          activity('Kegon Falls', '12:00', 'Nikko, Japan', 'Dramatic 97m waterfall.'),
          activity('Return to Tokyo', '16:00', 'Tokyo, Japan', 'Train back to the city.'),
        ],
      },
    ],
  };
}

function buildDemoTodos(planId: string): TodoItem[] {
  const now = new Date().toISOString();
  const base = { planId, createdAt: now, updatedAt: now };
  return [
    {
      ...base,
      id: uuidv4(),
      title: 'Book flights to Tokyo',
      category: 'Booking',
      status: 'done',
      autoGenerated: true,
    },
    {
      ...base,
      id: uuidv4(),
      title: 'Book accommodation for each night',
      category: 'Booking',
      status: 'done',
      autoGenerated: true,
    },
    {
      ...base,
      id: uuidv4(),
      title: 'Get travel insurance',
      category: 'Document',
      status: 'todo',
      autoGenerated: false,
    },
  ];
}

function buildDemoClipboard(planId: string): ClipboardItem[] {
  const now = new Date().toISOString();
  return [
    {
      id: uuidv4(),
      planId,
      type: 'Note',
      title: 'Hotel — Shinjuku Grand',
      body: 'Check-in: 3pm. Confirmation: TK-2025-88421. Free breakfast included. Address: 2-chome, Kabukicho, Shinjuku.',
      linkedDayIndex: 0,
      createdAt: now,
      updatedAt: now,
    },
  ];
}

/**
 * Seed the demo plan if this is a first launch. Idempotent and safe to call on
 * every boot. Any IndexedDB error is swallowed so app boot is never blocked.
 * Returns the seeded plan's id, or null if no seed was written.
 */
export async function seedDemoDataIfNeeded(): Promise<string | null> {
  try {
    // Flag guard: once seeded, never seed again — even if the user deletes
    // all their plans.
    if (localStorage.getItem(SEEDED_FLAG) === 'true') return null;

    // Never overwrite existing user data.
    const existingCount = await db.plans.filter((p) => !p.deleted).count();
    if (existingCount > 0) {
      // Data already present (e.g. migrated from before the flag existed) —
      // set the flag so we don't consider seeding again.
      localStorage.setItem(SEEDED_FLAG, 'true');
      return null;
    }

    const plan = buildDemoPlan();
    await db.plans.add(plan);
    await db.todos.bulkAdd(buildDemoTodos(plan.id));
    await db.clipboard.bulkAdd(buildDemoClipboard(plan.id));

    localStorage.setItem(SEEDED_FLAG, 'true');

    // Highlight the demo plan in the sidebar immediately.
    useAppStore.getState().setActivePlan(plan.id);

    return plan.id;
  } catch (err) {
    // Log and continue — a seed failure must never block app boot.
    // eslint-disable-next-line no-console
    console.error('Demo seed failed:', err);
    return null;
  }
}
