import { describe, it, expect } from 'vitest';
import type { ClipboardItem, Plan, TodoItem } from '../../db';
import { buildTripFile, parseTripFile, tripFileName, tripFromFile, TripFileError } from '../tripTransfer';

const plan: Plan = {
  id: 'p1', name: 'Tokyo', destination: 'Tokyo, Japan', country: 'Japan',
  startDate: '2026-10-11', endDate: '2026-10-13',
  createdAt: '2026-01-01T00:00:00.000Z', updatedAt: '2026-01-01T00:00:00.000Z', deleted: false,
  itinerary: [{ dayIndex: 0, label: 'Day 1', activities: [
    { id: 'a1', name: 'Meiji Shrine', time: 'morning', locationName: 'Shibuya', notes: '', pinnedToTodo: true },
  ] }],
};
const todo: TodoItem = {
  id: 't1', planId: 'p1', title: 'Book Meiji tour', category: 'Booking', status: 'todo',
  autoGenerated: true, sourceActivityId: 'a1', sourceDayIndex: 0, createdAt: '2026-01-01', updatedAt: '2026-01-01',
};
const pass: ClipboardItem = {
  id: 'c1', planId: 'p1', type: 'Boarding Pass', title: 'NH 106', body: 'Seat 32A',
  fileBlob: new Blob(['%PDF']), fileName: 'boarding.pdf', fileSize: 4,
  linkedDayIndex: 0, linkedActivityId: 'a1', createdAt: '2026-01-01', updatedAt: '2026-01-01',
};

describe('a trip as a file', () => {
  const file = buildTripFile(plan, [todo], [pass], new Date('2026-10-07T00:00:00Z'));

  it('carries the itinerary, to-dos and clipboard words', () => {
    expect(file.plan.itinerary[0].activities[0].name).toBe('Meiji Shrine');
    expect(file.todos[0].title).toBe('Book Meiji tour');
    expect(file.clipboard[0].title).toBe('NH 106');
  });

  // Personal documents, and large: they stay on the device they were added on.
  it('leaves attached documents out, and says one was there', () => {
    const c = file.clipboard[0] as Record<string, unknown>;
    expect(c.fileBlob).toBeUndefined();
    expect(c.fileName).toBeUndefined();
    expect(c.fileSize).toBeUndefined();
    expect(c.body).toBe('Seat 32A\n\n(Attached file not included: boarding.pdf)');
  });

  it('holds nothing about AI keys', () => {
    expect(JSON.stringify(file)).not.toMatch(/api.?key|ciphertext|aitp_/i);
  });

  it('survives being written and read back', () => {
    expect(parseTripFile(JSON.stringify(file)).plan.destination).toBe('Tokyo, Japan');
  });

  it('is named after the place and the start date', () => {
    expect(tripFileName(plan)).toBe('tokyo-2026-10-11.journ.json');
    expect(tripFileName({ destination: 'Percé, Québec', startDate: '2026-07-01' })).toBe('perce-2026-07-01.journ.json');
  });
});

describe('opening a trip file', () => {
  const file = buildTripFile(plan, [todo], [pass]);
  let n = 0;
  const { plan: p, todos, clipboard } = tripFromFile(file, new Date('2026-10-07T00:00:00Z'), () => `new-${++n}`);

  // Importing twice, or into the browser it came from, must add a trip, not overwrite one.
  it('gives the trip and everything in it new ids', () => {
    expect(p.id).not.toBe('p1');
    expect(p.itinerary[0].activities[0].id).not.toBe('a1');
    expect(todos[0].id).not.toBe('t1');
    expect(clipboard[0].id).not.toBe('c1');
  });

  it('keeps the links between them', () => {
    const actId = p.itinerary[0].activities[0].id;
    expect(todos[0].planId).toBe(p.id);
    expect(todos[0].sourceActivityId).toBe(actId);
    expect(clipboard[0].planId).toBe(p.id);
    expect(clipboard[0].linkedActivityId).toBe(actId);
  });

  it('is a live trip, dated now', () => {
    expect(p.deleted).toBe(false);
    expect(p.createdAt).toBe('2026-10-07T00:00:00.000Z');
  });
});

describe('a file that is not a trip', () => {
  it.each([
    ['not json', /could not be read as JSON/],
    ['{"hello":1}', /not a journ.ai trip/],
    [JSON.stringify({ kind: 'journ.ai trip', version: 99, plan }), /newer version/],
    [JSON.stringify({ kind: 'journ.ai trip', version: 1, plan: { destination: 'X' } }), /missing its destination, dates or itinerary/],
  ])('is turned away with a reason: %s', (text, reason) => {
    expect(() => parseTripFile(text)).toThrow(TripFileError);
    expect(() => parseTripFile(text)).toThrow(reason);
  });
});
