import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent } from '../../../test/render';
import { MemoryRouter } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import Button from '../Button';
import ActivityCard from '../../itinerary/ActivityCard';
import TodoList from '../../todo/TodoList';
import { db, type TodoItem } from '../../../db';

vi.mock('dexie-react-hooks');

const plan = { destination: 'Percé', country: 'Canada' };
const act = {
  id: 'a1', name: 'Rocher Percé', time: 'morning',
  locationName: 'Percé', notes: '', pinnedToTodo: false,
};
const todo: TodoItem = {
  id: 't1', planId: 'p1', title: 'Book the ferry', category: 'Booking',
  status: 'todo', autoGenerated: false, createdAt: '', updatedAt: '',
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.spyOn(db.todos, 'update').mockResolvedValue(1);
});

/*
 * Three surfaces did the same job three ways: an activity ended in a text link
 * reading "Done", a to-do ended in nothing and saved silently on blur, and a
 * clipboard item ended in a full-width accent slab. Only one of them said what
 * pressing it would do.
 */
describe('every editor ends the same way', () => {
  it('the itinerary card says Save', () => {
    render(<ActivityCard act={act} plan={plan} onDel={vi.fn()} onUpd={vi.fn()} onPin={vi.fn()} />);
    fireEvent.click(screen.getByLabelText('Edit activity'));
    expect(screen.getByTestId('activity-save-btn')).toHaveTextContent('Save');
    expect(screen.queryByText('Done')).not.toBeInTheDocument();
  });

  it('the to-do says Save, instead of saving where nobody can see it', () => {
    vi.mocked(useLiveQuery).mockReturnValue([todo]);
    render(<MemoryRouter><TodoList planId="p1" /></MemoryRouter>);
    fireEvent.click(screen.getByTestId('task-edit'));
    expect(screen.getByTestId('task-save-btn')).toHaveTextContent('Save');
  });

  it('offers a way out of each without saving', () => {
    render(<ActivityCard act={act} plan={plan} onDel={vi.fn()} onUpd={vi.fn()} onPin={vi.fn()} />);
    fireEvent.click(screen.getByLabelText('Edit activity'));
    expect(screen.getByTestId('activity-cancel-btn')).toBeInTheDocument();
  });

  it('leaves a to-do untouched when the edit is abandoned', () => {
    vi.mocked(useLiveQuery).mockReturnValue([todo]);
    render(<MemoryRouter><TodoList planId="p1" /></MemoryRouter>);
    fireEvent.click(screen.getByTestId('task-edit'));
    fireEvent.change(screen.getByLabelText('Edit title'), { target: { value: 'Changed' } });
    fireEvent.click(screen.getByTestId('task-cancel-btn'));
    expect(db.todos.update).not.toHaveBeenCalled();
  });
});

describe('the button itself', () => {
  // A full-width primary reads as the end of a whole flow — signing up,
  // checking out — and confirming a title edit is not that.
  it('sizes to its label rather than its container', () => {
    render(<Button>Save</Button>);
    expect(screen.getByRole('button').className).not.toContain('w-full');
  });

  it('goes full width only when asked', () => {
    render(<Button fullWidth>Save item</Button>);
    expect(screen.getByRole('button').className).toContain('w-full');
  });

  // Solid danger fills take the inverse ink: a label on this red measured
  // 3.44 against ink-primary, failing AA while asking for something
  // irreversible.
  it('labels a danger fill in ink that can be read on it', () => {
    render(<Button variant="danger">Delete</Button>);
    const cls = screen.getByRole('button').className;
    expect(cls).toContain('bg-status-danger');
    expect(cls).toContain('text-ink-inverse');
  });

  it('defaults to a real button rather than a form submit', () => {
    render(<Button>Save</Button>);
    expect(screen.getByRole('button')).toHaveAttribute('type', 'button');
  });

  it('can still submit a form when that is the job', () => {
    render(<Button type="submit">Save</Button>);
    expect(screen.getByRole('button')).toHaveAttribute('type', 'submit');
  });
});
