import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '../../../test/render';
import { MemoryRouter } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import TodoList from '../../todo/TodoList';
import ClipboardCard from '../../clipboard/ClipboardCard';
import { db, type TodoItem, type ClipboardItem } from '../../../db';

vi.mock('dexie-react-hooks');

const todo = (over: Partial<TodoItem> = {}): TodoItem => ({
  id: 't1', planId: 'p1', title: 'Book the ferry', category: 'Booking',
  status: 'todo', autoGenerated: false, createdAt: '', updatedAt: '', ...over,
});

const clip = (over: Partial<ClipboardItem> = {}): ClipboardItem => ({
  id: 'c1', planId: 'p1', type: 'Hotel', title: 'Auberge booking',
  createdAt: '', updatedAt: '', ...over,
});

const showTodos = (items: TodoItem[]) => {
  vi.mocked(useLiveQuery).mockReturnValue(items);
  return render(<MemoryRouter><TodoList planId="p1" /></MemoryRouter>);
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.spyOn(db.todos, 'update').mockResolvedValue(1);
  vi.spyOn(db.todos, 'delete').mockResolvedValue(undefined);
});

/*
 * Deleting a to-do was one button revealed on hover — unreachable by pointer
 * until you found it, and never obvious. Editing was hidden behind clicking
 * the title, which nothing suggested. A clipboard card had no actions at all;
 * everything was a screen deep in the detail view.
 */
describe('to-do cards carry their actions on the edge', () => {
  it('offers edit, pin and delete', () => {
    showTodos([todo()]);
    const rail = screen.getByTestId('task-actions');
    expect(rail).toContainElement(screen.getByTestId('task-edit'));
    expect(rail).toContainElement(screen.getByTestId('task-pin'));
    expect(rail).toContainElement(screen.getByTestId('task-delete'));
  });

  it('opens the title for editing', () => {
    showTodos([todo()]);
    fireEvent.click(screen.getByTestId('task-edit'));
    expect(screen.getByLabelText('Edit title')).toHaveValue('Book the ferry');
  });

  // The list is one the app keeps adding to on its own, so the one or two
  // things that matter get lost in it.
  it('pins a task, and says which are pinned', async () => {
    showTodos([todo()]);
    fireEvent.click(screen.getByTestId('task-pin'));
    await waitFor(() => expect(db.todos.update).toHaveBeenCalledWith('t1', expect.objectContaining({ pinned: true })));
  });

  it('unpins one that already is', async () => {
    showTodos([todo({ pinned: true })]);
    expect(screen.getByTestId('task-pinned-flag')).toBeInTheDocument();
    fireEvent.click(screen.getByTestId('task-pin'));
    await waitFor(() => expect(db.todos.update).toHaveBeenCalledWith('t1', expect.objectContaining({ pinned: false })));
  });

  it('sorts pinned tasks to the top of their category', () => {
    showTodos([
      todo({ id: 'a', title: 'First added' }),
      todo({ id: 'b', title: 'Pinned one', pinned: true }),
    ]);
    const titles = screen.getAllByTestId('task-row').map(r => r.textContent);
    expect(titles[0]).toContain('Pinned one');
  });

  it('names the task in each control, since the rail has no room for text', () => {
    showTodos([todo()]);
    expect(screen.getByLabelText('Delete: Book the ferry')).toBeInTheDocument();
    expect(screen.getByLabelText('Pin to top: Book the ferry')).toBeInTheDocument();
  });
});

describe('clipboard cards carry theirs too', () => {
  const handlers = { onEdit: vi.fn(), onPin: vi.fn(), onDelete: vi.fn(), onClick: vi.fn() };

  it('offers edit, pin and delete', () => {
    render(<ClipboardCard item={clip()} {...handlers} />);
    const rail = screen.getByTestId('clipboard-actions');
    expect(rail).toContainElement(screen.getByTestId('clipboard-edit'));
    expect(rail).toContainElement(screen.getByTestId('clipboard-pin'));
    expect(rail).toContainElement(screen.getByTestId('clipboard-delete'));
  });

  it('calls each without opening the card', () => {
    render(<ClipboardCard item={clip()} {...handlers} />);
    fireEvent.click(screen.getByTestId('clipboard-delete'));
    expect(handlers.onDelete).toHaveBeenCalled();
    expect(handlers.onClick).not.toHaveBeenCalled();
  });

  // Pin means linked to a day here — the itinerary card's Pin in reverse.
  it('shows a linked item as pinned, and offers to unlink it', () => {
    render(<ClipboardCard item={clip({ linkedDayIndex: 1 })} {...handlers} />);
    expect(screen.getByTestId('clipboard-pin')).toHaveAttribute('aria-pressed', 'true');
    expect(screen.getByLabelText(/Unlink Auberge booking/)).toBeInTheDocument();
  });

  it('offers to link one that is not', () => {
    render(<ClipboardCard item={clip()} {...handlers} />);
    expect(screen.getByTestId('clipboard-pin')).not.toHaveAttribute('aria-pressed');
    expect(screen.getByLabelText(/Link Auberge booking/)).toBeInTheDocument();
  });

  // The card is a button; its controls cannot be nested inside it.
  it('keeps the rail outside the card button', () => {
    render(<ClipboardCard item={clip()} {...handlers} />);
    const open = screen.getByLabelText('Hotel: Auberge booking');
    expect(open).not.toContainElement(screen.getByTestId('clipboard-delete'));
  });

  it('renders no rail at all when nothing can be done', () => {
    render(<ClipboardCard item={clip()} onClick={vi.fn()} />);
    expect(screen.queryByTestId('clipboard-actions')).not.toBeInTheDocument();
  });
});
