import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '../../../test/render';
import { MemoryRouter } from 'react-router-dom';
import { useLiveQuery } from 'dexie-react-hooks';
import TodoList from '../../todo/TodoList';
import ClipboardCard from '../../clipboard/ClipboardCard';
import { db, type TodoItem, type ClipboardItem } from '../../../db';

vi.mock('dexie-react-hooks');

const todo = (over: Partial<TodoItem> = {}): TodoItem => ({
  id: 't1', planId: 'p1', title: 'Book the ferry', category: 'Booking',
  status: 'todo', autoGenerated: false, createdAt: '', updatedAt: '', ...over,
});

const clip = (over: Partial<ClipboardItem> = {}): ClipboardItem => ({
  id: 'c1', planId: 'p1', type: 'Hotel', title: 'Auberge booking',
  createdAt: '', updatedAt: '', ...over,
});

const showTodos = (items: TodoItem[]) => {
  vi.mocked(useLiveQuery).mockReturnValue(items);
  return render(<MemoryRouter><TodoList planId="p1" /></MemoryRouter>);
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.spyOn(db.todos, 'update').mockResolvedValue(1);
  vi.spyOn(db.todos, 'delete').mockResolvedValue(undefined);
});


/** A row's actions live behind its "More actions" menu; open it first. */
const openMenu = (name: RegExp | string = /More actions for/, index = 0) =>
  fireEvent.click(screen.getAllByRole('button', { name: typeof name === 'string' ? `More actions for ${name}` : name })[index]);

/*
 * Deleting a to-do was once one button revealed on hover, and a clipboard card
 * had no actions at all. Then every row got a rail of three icons with a red
 * bin, which made a list read as controls. Now each row has one "More actions"
 * button, always visible, and the menu names each action in words.
 */
describe('to-do rows keep their actions in one menu', () => {
  it('offers edit, pin and delete', () => {
    showTodos([todo()]);
    expect(screen.getByTestId('task-actions')).toContainElement(screen.getByRole('button', { name: 'More actions for Book the ferry' }));
    openMenu('Book the ferry');
    const menu = screen.getByRole('menu');
    expect(menu).toContainElement(screen.getByTestId('task-edit'));
    expect(menu).toContainElement(screen.getByTestId('task-pin'));
    expect(menu).toContainElement(screen.getByTestId('task-delete'));
  });

  it('opens the title for editing', () => {
    showTodos([todo()]);
    openMenu('Book the ferry');
    fireEvent.click(screen.getByTestId('task-edit'));
    expect(screen.getByLabelText('Edit title')).toHaveValue('Book the ferry');
  });

  // The list is one the app keeps adding to on its own, so the one or two
  // things that matter get lost in it.
  it('pins a task, and says which are pinned', async () => {
    showTodos([todo()]);
    openMenu('Book the ferry');
    fireEvent.click(screen.getByTestId('task-pin'));
    await waitFor(() => expect(db.todos.update).toHaveBeenCalledWith('t1', expect.objectContaining({ pinned: true })));
  });

  it('unpins one that already is', async () => {
    showTodos([todo({ pinned: true })]);
    expect(screen.getByTestId('task-pinned-flag')).toBeInTheDocument();
    openMenu('Book the ferry');
    expect(screen.getByTestId('task-pin')).toHaveTextContent('Unpin');
    fireEvent.click(screen.getByTestId('task-pin'));
    await waitFor(() => expect(db.todos.update).toHaveBeenCalledWith('t1', expect.objectContaining({ pinned: false })));
  });

  it('sorts pinned tasks to the top of their category', () => {
    showTodos([
      todo({ id: 'a', title: 'First added' }),
      todo({ id: 'b', title: 'Pinned one', pinned: true }),
    ]);
    const titles = screen.getAllByTestId('task-row').map(r => r.textContent);
    expect(titles[0]).toContain('Pinned one');
  });

  it('names the task in each action', () => {
    showTodos([todo()]);
    openMenu('Book the ferry');
    expect(screen.getByLabelText('Delete: Book the ferry')).toBeInTheDocument();
    expect(screen.getByLabelText('Pin to top: Book the ferry')).toBeInTheDocument();
  });
});

describe('clipboard cards do the same', () => {
  const handlers = { onEdit: vi.fn(), onPin: vi.fn(), onDelete: vi.fn(), onClick: vi.fn() };

  it('offers edit, link and delete', () => {
    render(<ClipboardCard item={clip()} {...handlers} />);
    openMenu('Auberge booking');
    const menu = screen.getByRole('menu');
    expect(menu).toContainElement(screen.getByTestId('clipboard-edit'));
    expect(menu).toContainElement(screen.getByTestId('clipboard-pin'));
    expect(menu).toContainElement(screen.getByTestId('clipboard-delete'));
  });

  it('acts without opening the card', () => {
    render(<ClipboardCard item={clip()} {...handlers} />);
    openMenu('Auberge booking');
    fireEvent.click(screen.getByTestId('clipboard-delete'));
    expect(handlers.onDelete).toHaveBeenCalled();
    expect(handlers.onClick).not.toHaveBeenCalled();
  });

  // The link is a state, so it shows on the card, not only in the menu.
  it('shows a linked item as linked, and offers to unlink it', () => {
    render(<ClipboardCard item={clip({ linkedDayIndex: 1 })} {...handlers} />);
    expect(screen.getByTestId('clipboard-linked-flag')).toHaveTextContent('Linked to Day 2');
    openMenu('Auberge booking');
    expect(screen.getByLabelText(/Unlink Auberge booking/)).toBeInTheDocument();
  });

  it('offers to link one that is not', () => {
    render(<ClipboardCard item={clip()} {...handlers} />);
    expect(screen.queryByTestId('clipboard-linked-flag')).not.toBeInTheDocument();
    openMenu('Auberge booking');
    expect(screen.getByLabelText(/Link Auberge booking/)).toBeInTheDocument();
  });

  // The card is a button; its controls cannot be nested inside it.
  it('keeps the menu outside the card button', () => {
    render(<ClipboardCard item={clip()} {...handlers} />);
    const open = screen.getByLabelText('Hotel: Auberge booking');
    expect(open).not.toContainElement(screen.getByRole('button', { name: 'More actions for Auberge booking' }));
  });

  it('shows no menu at all when nothing can be done', () => {
    render(<ClipboardCard item={clip()} onClick={vi.fn()} />);
    expect(screen.queryByTestId('clipboard-actions')).not.toBeInTheDocument();
  });
});

// The rows clipped their content for the old rail, and the opened menu was
// cut off at the row's edge, showing one item of three.
describe('an open menu is not cut off', () => {
  it('does not clip a to-do row, and lifts it while its menu is open', () => {
    showTodos([todo()]);
    const row = screen.getByTestId('task-row');
    expect(row.className).not.toContain('overflow-hidden');
    expect(row.className).toContain('has-[[aria-expanded=true]]:z-20');
  });

  it('does not clip a clipboard card', () => {
    render(<ClipboardCard item={clip()} onEdit={vi.fn()} onClick={vi.fn()} />);
    expect(screen.getByTestId('clipboard-card').className).not.toContain('overflow-hidden');
  });
});

describe('what the colours say', () => {
  // Red belongs where the choice is made, not on every row at rest.
  it('keeps red off the row, and puts it on Delete in the menu', () => {
    showTodos([todo()]);
    expect(screen.getByTestId('task-row').querySelector('.text-status-danger')).toBeNull();
    openMenu('Book the ferry');
    expect(screen.getByTestId('task-delete').className).toContain('text-status-danger');
    expect(screen.getByTestId('task-edit').className).not.toContain('text-status-danger');
  });

  it('sets Delete apart from the other actions', () => {
    showTodos([todo()]);
    openMenu('Book the ferry');
    const items = screen.getAllByRole('menuitem');
    expect(items.at(-1)).toBe(screen.getByTestId('task-delete'));
    expect(screen.getByRole('separator')).toBeInTheDocument();
  });
});
