import { useState, useRef } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { PlusCircle, Trash2, CheckSquare, Square } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';
import { useNavigate } from 'react-router-dom';
import { db, type TodoItem, type Plan } from '../../db';
import Toast from '../ui/Toast';

interface Props { planId: string; }

const CATS = ['Booking', 'Document', 'Packing', 'Other'] as const;
type Cat = (typeof CATS)[number];

const CAT_COLOR: Record<Cat, string> = {
  Booking: 'border-cyan-400',
  Document: 'border-sky-400',
  Packing: 'border-emerald-400',
  Other: 'border-slate-600',
};

function AddForm({ planId, onDone }: { planId: string; onDone: () => void }) {
  const [title, setTitle] = useState('');
  const [due, setDue] = useState('');
  const [cat, setCat] = useState<Cat>('Other');
  const [err, setErr] = useState('');
  const [saving, setSaving] = useState(false);
  const today = new Date().toISOString().split('T')[0];

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) { setErr('Title is required'); return; }
    setSaving(true);
    try {
      const now = new Date().toISOString();
      await db.todos.add({ id: uuidv4(), planId, title: title.trim(), category: cat, status: 'todo', dueDate: due || undefined, autoGenerated: false, createdAt: now, updatedAt: now });
      setTitle(''); setDue(''); setCat('Other'); onDone();
    } finally { setSaving(false); }
  };

  return (
    <form onSubmit={submit} className="bg-surface-overlay border border-white/10 rounded-xl p-4 space-y-3" data-testid="add-task-form">
      <div>
        <input value={title} onChange={e => { setTitle(e.target.value); setErr(''); }} placeholder="Task title"
          className="w-full bg-surface-raised border border-white/10 rounded-xl px-3 py-2 text-sm text-ink-primary placeholder:text-ink-muted focus:outline-none focus:ring-2 focus:ring-accent/50"
          data-testid="task-title-input" aria-label="Task title" />
        {err && <p role="alert" className="mt-1 text-xs text-status-danger">{err}</p>}
      </div>
      <div className="flex gap-2">
        <input type="date" value={due} onChange={e => setDue(e.target.value)}
          className={`flex-1 bg-surface-raised border rounded-xl px-3 py-2 text-sm text-ink-primary focus:outline-none focus:ring-2 focus:ring-accent/50 ${due && due < today ? 'border-status-warning/50' : 'border-white/10'}`}
          aria-label="Due date" />
        {due && due < today && <p className="text-xs text-status-warning self-center">Past</p>}
        <select value={cat} onChange={e => setCat(e.target.value as Cat)} aria-label="Category"
          className="bg-surface-raised border border-white/10 rounded-xl px-3 py-2 text-sm text-ink-primary focus:outline-none focus:ring-2 focus:ring-accent/50">
          {CATS.map(c => <option key={c} value={c}>{c}</option>)}
        </select>
      </div>
      <button type="submit" disabled={saving} data-testid="save-task-btn"
        className="w-full bg-accent hover:bg-accent-light disabled:opacity-60 text-ink-inverse font-semibold py-2 rounded-xl text-sm">
        {saving ? 'Saving…' : 'Add Task'}
      </button>
    </form>
  );
}

interface RowProps {
  item: TodoItem;
  plan: Plan | undefined;
  onToggle: () => void;
  onDel: () => void;
  onUpd: (t: string) => void;
  onNavigateToDay: (dayIndex: number) => void;
}

function Row({ item, plan, onToggle, onDel, onUpd, onNavigateToDay }: RowProps) {
  const [ed, setEd] = useState(false);
  const [val, setVal] = useState(item.title);
  const ref = useRef<HTMLInputElement>(null);
  const today = new Date().toISOString().split('T')[0];
  const pastDue = item.dueDate && item.dueDate < today && item.status !== 'done';
  const color = CAT_COLOR[item.category as Cat] ?? CAT_COLOR.Other;

  // Determine if the pinned source activity still exists
  const sourceExists = item.sourceActivityId
    ? plan?.itinerary?.some(day =>
        day.activities.some(act => act.id === item.sourceActivityId)
      ) ?? null // null = plan not yet loaded, show badge normally
    : null;

  const handleBadgeClick = () => {
    if (item.sourceDayIndex !== undefined) {
      onNavigateToDay(item.sourceDayIndex);
    }
  };

  return (
    <div className={`flex items-center gap-3 py-2.5 px-3 rounded-xl border-l-2 ${color} bg-surface-raised group hover:bg-surface-overlay transition-colors`} data-testid="task-row">
      <button onClick={onToggle} className="shrink-0 text-ink-muted hover:text-accent" aria-label={item.status === 'done' ? 'Mark incomplete' : 'Mark complete'}>
        {item.status === 'done' ? <CheckSquare size={18} className="text-status-success" /> : <Square size={18} />}
      </button>
      <div className="flex-1 min-w-0">
        {ed
          ? <input ref={ref} value={val} onChange={e => setVal(e.target.value)} onBlur={() => { if (val.trim()) onUpd(val.trim()); else setVal(item.title); setEd(false); }} onKeyDown={e => e.key === 'Enter' && ref.current?.blur()}
              className="w-full bg-surface-overlay border border-accent/40 rounded-lg px-2 py-0.5 text-sm text-ink-primary focus:outline-none" aria-label="Edit title" autoFocus />
          : <div>
              <button onClick={() => setEd(true)} className={`text-sm text-left w-full ${item.status === 'done' ? 'line-through text-ink-muted' : 'text-ink-primary'}`}>{item.title}</button>
              <div className="flex items-center gap-2 mt-0.5 flex-wrap">
                {item.autoGenerated && <span className="text-xs font-semibold text-accent bg-accent/10 px-2 py-0.5 rounded-full">Generated</span>}
                {item.sourceActivityId && (
                  sourceExists === false
                    ? <span className="text-xs text-ink-muted bg-surface-overlay px-2 py-0.5 rounded-full">📍 Source removed</span>
                    : <button
                        onClick={handleBadgeClick}
                        className="text-xs text-ink-muted bg-surface-overlay px-2 py-0.5 rounded-full hover:bg-surface-raised transition-colors"
                        aria-label={`Go to Day ${(item.sourceDayIndex ?? 0) + 1} in itinerary`}
                        data-testid="itinerary-badge"
                      >
                        📍 From itinerary{item.sourceDayIndex !== undefined ? ` · Day ${item.sourceDayIndex + 1}` : ''}
                      </button>
                )}
                {item.dueDate && <span className={`text-xs ${pastDue ? 'text-status-warning' : 'text-ink-muted'}`}>Due {item.dueDate}</span>}
              </div>
            </div>
        }
      </div>
      <button onClick={onDel} className="shrink-0 p-1 rounded-lg text-ink-muted hover:text-status-danger opacity-0 group-hover:opacity-100 transition-all" aria-label={`Delete: ${item.title}`}>
        <Trash2 size={14} />
      </button>
    </div>
  );
}

export default function TodoList({ planId }: Props) {
  const [showAdd, setShowAdd] = useState(false);
  const [toast, setToast] = useState<{ msg: string; undo?: () => void } | null>(null);
  const navigate = useNavigate();
  const todos = useLiveQuery(() => db.todos.where('planId').equals(planId).sortBy('createdAt'), [planId]);
  const plan = useLiveQuery(() => db.plans.get(planId), [planId]);

  if (todos === undefined) return (
    <div className="flex items-center justify-center h-full">
      <div className="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin" aria-label="Loading" />
    </div>
  );

  const total = todos.length;
  const doneCount = todos.filter(t => t.status === 'done').length;
  const pct = total > 0 ? Math.round((doneCount / total) * 100) : 0;
  const allDone = total > 0 && doneCount === total;

  const toggle = (item: TodoItem) =>
    db.todos.update(item.id, { status: item.status === 'done' ? 'todo' : 'done', updatedAt: new Date().toISOString() });

  const del = async (item: TodoItem) => {
    await db.todos.delete(item.id);
    setToast({ msg: 'Task deleted', undo: async () => { await db.todos.add(item); setToast(null); } });
  };

  const upd = (item: TodoItem, title: string) =>
    db.todos.update(item.id, { title, updatedAt: new Date().toISOString() });

  const navigateToDay = (dayIndex: number) => {
    navigate(`/plan/${planId}/itinerary`);
    // Scroll happens after navigation; use a short timeout to allow the DOM to update
    setTimeout(() => {
      document.getElementById(`day-${dayIndex}`)?.scrollIntoView({ behavior: 'smooth' });
    }, 150);
  };

  return (
    <div className="flex flex-col h-full" data-testid="todo-list">
      <div className="px-4 py-4 border-b border-white/5 shrink-0">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-lg font-semibold text-ink-primary">To-Do</h2>
          <button onClick={() => setShowAdd(v => !v)} className="flex items-center gap-1.5 text-sm text-accent hover:text-accent-light" data-testid="add-task-btn" aria-label="Add task">
            <PlusCircle size={16} /> Add task
          </button>
        </div>
        {total > 0 && (
          <div>
            <div className="flex justify-between text-xs text-ink-muted mb-1">
              <span>{doneCount} of {total} complete</span><span>{pct}%</span>
            </div>
            <div className="h-1.5 bg-surface-overlay rounded-full overflow-hidden" role="progressbar" aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100}>
              <div className="h-full bg-accent transition-all rounded-full" style={{ width: `${pct}%` }} />
            </div>
          </div>
        )}
        {allDone && (
          <div className="mt-3 p-3 bg-status-success/10 border border-status-success/20 rounded-xl text-center">
            <p className="text-sm font-semibold text-status-success">✓ All done!</p>
          </div>
        )}
      </div>

      {showAdd && (
        <div className="px-4 py-3 border-b border-white/5 shrink-0">
          <AddForm planId={planId} onDone={() => setShowAdd(false)} />
        </div>
      )}

      <div className="flex-1 overflow-y-auto px-4 py-4 space-y-6">
        {total === 0 && (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <CheckSquare size={36} className="text-accent-muted mb-3" aria-hidden="true" />
            <p className="text-sm text-ink-muted">No tasks yet</p>
          </div>
        )}
        {CATS.map(cat => {
          const items = todos.filter(t => t.category === cat);
          if (!items.length) return null;
          return (
            <section key={cat} aria-label={`${cat} tasks`}>
              <h3 className="text-sm font-semibold text-ink-secondary mb-2 uppercase tracking-wider">{cat}</h3>
              <div className="space-y-1.5">
                {items.filter(t => t.status !== 'done').map(item => (
                  <Row key={item.id} item={item} plan={plan} onToggle={() => toggle(item)} onDel={() => del(item)} onUpd={t => upd(item, t)} onNavigateToDay={navigateToDay} />
                ))}
                {items.filter(t => t.status === 'done').map(item => (
                  <Row key={item.id} item={item} plan={plan} onToggle={() => toggle(item)} onDel={() => del(item)} onUpd={t => upd(item, t)} onNavigateToDay={navigateToDay} />
                ))}
              </div>
            </section>
          );
        })}
      </div>

      {toast && <Toast message={toast.msg} onDismiss={() => setToast(null)} action={toast.undo ? { label: 'Undo', onClick: toast.undo } : undefined} />}
    </div>
  );
}
