import { useState, useRef } from 'react';
import Modal, { AddButton } from '../ui/Modal';
import DetailModal, { DetailRow } from '../ui/DetailModal';
import { fieldClass, fieldClassAuto } from '../ui/formStyles';
import { useIsMobile } from '../../hooks/useIsMobile';
import Button from '../ui/Button';
import { CardActionRail, CardAction } from '../ui/CardActionRail';
import { useLiveQuery } from 'dexie-react-hooks';
import { PlusCircle, Trash2, CheckSquare, Square, Pin, Pencil } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';
import { useNavigate } from 'react-router-dom';
import { db, type TodoItem, type Plan } from '../../db';
import Toast from '../ui/Toast';
import { scrollBehavior } from '../../utils/motion';

interface Props { planId: string; }

const CATS = ['Booking', 'Document', 'Packing', 'Other'] as const;
type Cat = (typeof CATS)[number];

const CAT_COLOR: Record<Cat, string> = {
  Booking: 'border-l-category-cyan',
  Document: 'border-l-category-sky',
  Packing: 'border-l-category-emerald',
  Other: 'border-l-category-slate',
};

function AddForm({ planId, onDone }: { planId: string; onDone: () => void }) {
  const isMobile = useIsMobile();
  const [title, setTitle] = useState('');
  const [due, setDue] = useState('');
  const [cat, setCat] = useState<Cat>('Other');
  const [err, setErr] = useState('');
  const [saving, setSaving] = useState(false);
  const today = new Date().toISOString().split('T')[0];

  const submit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) { setErr('Title is required'); return; }
    setSaving(true);
    try {
      const now = new Date().toISOString();
      await db.todos.add({ id: uuidv4(), planId, title: title.trim(), category: cat, status: 'todo', dueDate: due || undefined, autoGenerated: false, createdAt: now, updatedAt: now });
      setTitle(''); setDue(''); setCat('Other'); onDone();
    } finally { setSaving(false); }
  };

  /*
   * Was a form that unfolded inside the list, ending in a full-width "Add
   * Task" slab and offering no way out but pressing the trigger again. Adding
   * a task is the same job as adding an activity, so it is the same dialog.
   */
  return (
    <Modal title="Add task" onClose={onDone} anchor={isMobile ? 'top' : 'center'}>
    <form onSubmit={submit} className="space-y-3" data-testid="add-task-form">
      <div>
        <input value={title} onChange={e => { setTitle(e.target.value); setErr(''); }} placeholder="Task title"
          className={fieldClass}
          data-testid="task-title-input" aria-label="Task title" />
        {err && <p role="alert" className="mt-1 text-xs text-status-danger">{err}</p>}
      </div>
      <div className="flex gap-2">
        {/* A date and a category are both short. Paired on one row rather
            than stacked, which is what the extra width is for. */}
        <input type="date" value={due} onChange={e => setDue(e.target.value)}
          className={`flex-1 ${fieldClassAuto} ${due && due < today ? '!border-status-warning/50' : ''}`}
          aria-label="Due date" />
        {due && due < today && <p className="text-xs text-status-warning self-center">Past</p>}
        <select value={cat} onChange={e => setCat(e.target.value as Cat)} aria-label="Category"
          className={fieldClassAuto}>
          {CATS.map(c => <option key={c} value={c}>{c}</option>)}
        </select>
      </div>
      <div className="flex gap-2 pt-1">
        <Button type="submit" disabled={saving} data-testid="save-task-btn">
          {saving ? 'Saving…' : 'Save'}
        </Button>
        <Button variant="secondary" onClick={onDone} data-testid="cancel-task-btn">Cancel</Button>
      </div>
    </form>
    </Modal>
  );
}

interface RowProps {
  item: TodoItem;
  plan: Plan | undefined;
  onToggle: () => void;
  onDel: () => void;
  onUpd: (t: string) => void;
  onPin: () => void;
  onNavigateToDay: (dayIndex: number) => void;
}

function Row({ item, plan, onToggle, onDel, onUpd, onPin, onNavigateToDay }: RowProps) {
  /**
   * Closed, reading the task, or changing it. The same two modes the itinerary
   * cards use, so a card behaves the same wherever it is.
   */
  const [detail, setDetail] = useState<null | 'view' | 'edit'>(null);
  const [val, setVal] = useState(item.title);
  const ref = useRef<HTMLInputElement>(null);

  const commit = () => {
    if (val.trim()) onUpd(val.trim());
    else setVal(item.title);
    setDetail(null);
  };
  const cancel = () => {
    setVal(item.title);
    setDetail(null);
  };
  const today = new Date().toISOString().split('T')[0];
  const pastDue = item.dueDate && item.dueDate < today && item.status !== 'done';
  const color = CAT_COLOR[item.category as Cat] ?? CAT_COLOR.Other;

  // Determine if the pinned source activity still exists
  const sourceExists = item.sourceActivityId
    ? plan?.itinerary?.some(day =>
        day.activities.some(act => act.id === item.sourceActivityId)
      ) ?? null // null = plan not yet loaded, show badge normally
    : null;

  const handleBadgeClick = () => {
    if (item.sourceDayIndex !== undefined) {
      onNavigateToDay(item.sourceDayIndex);
    }
  };

  return (
    <div className={`card-surface group flex items-stretch rounded-card border-l-2 overflow-hidden ${color}`} data-testid="task-row">
      <div className="flex-1 min-w-0 flex items-center gap-3 py-2.5 px-3">
      <button onClick={onToggle} className="shrink-0 text-ink-muted hover:text-accent" aria-label={item.status === 'done' ? 'Mark incomplete' : 'Mark complete'}>
        {item.status === 'done' ? <CheckSquare size={18} className="text-status-success" /> : <Square size={18} />}
      </button>
      <div className="flex-1 min-w-0">
        <div>
              {/* Opens what the task knows rather than an edit box. Tapping a
                  title used to drop straight into editing it, which is a
                  strange answer to "what is this?" and the only way to read a
                  long one. */}
              <button
                onClick={() => setDetail('view')}
                className={`text-sm text-left w-full ${item.status === 'done' ? 'line-through text-ink-muted' : 'text-ink-primary'}`}
                aria-label={`${item.title} — open details`}
                data-testid="task-title"
              >{item.title}</button>
              <div className="flex items-center gap-2 mt-0.5 flex-wrap">
                {item.pinned && <span className="text-xs font-semibold text-accent bg-accent/10 px-2 py-0.5 rounded-full" data-testid="task-pinned-flag">Pinned</span>}
                {item.autoGenerated && <span className="text-xs font-semibold text-accent bg-accent/10 px-2 py-0.5 rounded-full">Generated</span>}
                {item.sourceActivityId && (
                  sourceExists === false
                    ? <span className="text-xs text-ink-muted bg-surface-overlay px-2 py-0.5 rounded-full">📍 Source removed</span>
                    : <button
                        onClick={handleBadgeClick}
                        className="text-xs text-ink-muted bg-surface-overlay px-2 py-0.5 rounded-full hover:bg-surface-raised transition-colors"
                        aria-label={`Go to Day ${(item.sourceDayIndex ?? 0) + 1} in itinerary`}
                        data-testid="itinerary-badge"
                      >
                        📍 From itinerary{item.sourceDayIndex !== undefined ? ` · Day ${item.sourceDayIndex + 1}` : ''}
                      </button>
                )}
                {item.dueDate && <span className={`text-xs ${pastDue ? 'text-status-warning' : 'text-ink-muted'}`}>Due {item.dueDate}</span>}
              </div>
        </div>
      </div>
      </div>

      {/* The same binder edge the itinerary cards use. Deleting used to be a
          single button revealed on hover, which was unreachable by pointer
          until you found it and never obvious at all; editing was hidden
          behind clicking the title, which nothing suggested. */}
      <CardActionRail testId="task-actions">
        <CardAction
          icon={<Pin size={14} />}
          label={item.pinned ? `Unpin: ${item.title}` : `Pin to top: ${item.title}`}
          onClick={onPin}
          active={!!item.pinned}
          testId="task-pin"
        />
        <CardAction
          icon={<Pencil size={14} />}
          label={`Edit: ${item.title}`}
          onClick={() => setDetail('edit')}
          testId="task-edit"
        />
        <CardAction
          icon={<Trash2 size={14} />}
          label={`Delete: ${item.title}`}
          onClick={onDel}
          tone="danger"
          testId="task-delete"
        />
      </CardActionRail>

      {detail && (
        <DetailModal
          title={detail === 'edit' ? 'Edit task' : 'Task'}
          onClose={cancel}
          onEdit={() => setDetail('edit')}
          onDelete={() => { setDetail(null); onDel(); }}
          deleteLabel={`Delete: ${item.title}`}
          // A task has no place of its own, but one raised from an activity
          // has a day — which is the equivalent move, and the badge that
          // offered it was easy to miss among the others.
          goTo={item.sourceDayIndex !== undefined && sourceExists !== false
            ? { label: `Day ${item.sourceDayIndex + 1}`, onClick: () => { setDetail(null); onNavigateToDay(item.sourceDayIndex!); } }
            : null}
          testId="task-detail"
        >
          {detail === 'edit' ? (
            <div className="space-y-2" data-testid="task-edit-form">
              {/* Saving silently on blur meant the only way to find out whether
                  an edit had taken was to look. Now it says so, in the same
                  words the other two editors use. */}
              <input ref={ref} value={val} onChange={e => setVal(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') commit(); if (e.key === 'Escape') cancel(); }}
                className={fieldClass}
                aria-label="Edit title" autoFocus />
              <div className="flex gap-2 pt-1">
                <Button size="sm" onClick={commit} data-testid="task-save-btn">Save</Button>
                <Button size="sm" variant="secondary" onClick={cancel} data-testid="task-cancel-btn">Cancel</Button>
              </div>
            </div>
          ) : (
            <dl className="-mt-1">
              <DetailRow label="Task" testId="detail-title">{item.title}</DetailRow>
              <DetailRow label="Category">{item.category}</DetailRow>
              <DetailRow label="Status">
                {item.status === 'done' ? 'Complete' : 'Not done'}
              </DetailRow>
              {item.dueDate && (
                <DetailRow label="Due">
                  <span className={pastDue ? 'text-status-warning' : undefined}>
                    {item.dueDate}{pastDue ? ' — past due' : ''}
                  </span>
                </DetailRow>
              )}
              {item.sourceActivityId && (
                <DetailRow label="From">
                  {sourceExists === false
                    ? <span className="text-ink-muted">An activity that has since been removed</span>
                    : `The itinerary${item.sourceDayIndex !== undefined ? `, day ${item.sourceDayIndex + 1}` : ''}`}
                </DetailRow>
              )}
              {(item.pinned || item.autoGenerated) && (
                <DetailRow label="Flags">
                  <span className="flex flex-wrap items-center gap-2">
                    {item.pinned && (
                      <span className="text-xs text-accent bg-accent/10 px-2 py-0.5 rounded-full">Pinned</span>
                    )}
                    {item.autoGenerated && (
                      <span className="text-xs text-accent bg-accent/10 px-2 py-0.5 rounded-full">
                        Added for you
                      </span>
                    )}
                  </span>
                </DetailRow>
              )}
            </dl>
          )}
        </DetailModal>
      )}
    </div>
  );
}

export default function TodoList({ planId }: Props) {
  const [showAdd, setShowAdd] = useState(false);
  const [toast, setToast] = useState<{ msg: string; undo?: () => void } | null>(null);
  const navigate = useNavigate();
  const todos = useLiveQuery(() => db.todos.where('planId').equals(planId).sortBy('createdAt'), [planId]);
  const plan = useLiveQuery(() => db.plans.get(planId), [planId]);

  if (todos === undefined) return (
    <div className="flex items-center justify-center h-full">
      <div className="w-8 h-8 border-2 border-accent border-t-transparent rounded-full animate-spin" aria-label="Loading" />
    </div>
  );

  const total = todos.length;
  /*
   * Pinned tasks sort to the top of their category. The list is one the app
   * keeps adding to on its own — booking reminders, entry requirements — so
   * the one or two things that actually matter get lost in it.
   */
  const pin = (item: TodoItem) =>
    db.todos.update(item.id, { pinned: !item.pinned, updatedAt: new Date().toISOString() });

  const byPinned = (a: TodoItem, b: TodoItem) => Number(!!b.pinned) - Number(!!a.pinned);

  const doneCount = todos.filter(t => t.status === 'done').length;
  const pct = total > 0 ? Math.round((doneCount / total) * 100) : 0;
  const allDone = total > 0 && doneCount === total;

  const toggle = (item: TodoItem) =>
    db.todos.update(item.id, { status: item.status === 'done' ? 'todo' : 'done', updatedAt: new Date().toISOString() });

  const del = async (item: TodoItem) => {
    await db.todos.delete(item.id);
    setToast({ msg: 'Task deleted', undo: async () => { await db.todos.add(item); setToast(null); } });
  };

  const upd = (item: TodoItem, title: string) =>
    db.todos.update(item.id, { title, updatedAt: new Date().toISOString() });

  const navigateToDay = (dayIndex: number) => {
    navigate(`/plan/${planId}/itinerary`);
    // Scroll happens after navigation; use a short timeout to allow the DOM to update
    setTimeout(() => {
      document.getElementById(`day-${dayIndex}`)?.scrollIntoView({ behavior: scrollBehavior() });
    }, 150);
  };

  return (
    <div className="flex flex-col h-full" data-testid="todo-list">
      <div className="px-4 py-4 border-b border-white/5 shrink-0">
        <div className="flex items-center justify-between mb-3">
          <h2 className="text-lg font-semibold text-ink-primary">To-Do</h2>

        </div>
        {total > 0 && (
          <div>
            <div className="flex justify-between text-xs text-ink-muted mb-1">
              <span>{doneCount} of {total} complete</span><span>{pct}%</span>
            </div>
            <div className="h-1.5 bg-surface-overlay rounded-full overflow-hidden" role="progressbar" aria-valuenow={pct} aria-valuemin={0} aria-valuemax={100}>
              <div className="h-full bg-accent transition-all rounded-full" style={{ width: `${pct}%` }} />
            </div>
          </div>
        )}
        {allDone && (
          <div className="mt-3 p-3 bg-status-success/10 border border-status-success/20 rounded-xl text-center">
            <p className="text-sm font-semibold text-status-success">✓ All done!</p>
          </div>
        )}
      </div>

      {showAdd && <AddForm planId={planId} onDone={() => setShowAdd(false)} />}

      <div className="flex-1 min-h-0 overflow-y-auto px-4 py-4 space-y-6">
        {/* The way in sits with the list rather than as a small accent link in
            the header, which is the least visible thing on screen at the
            moment someone is looking for how to start. */}
        <AddButton label="Add task" onClick={() => setShowAdd(true)} testId="add-task-btn" />
        {total === 0 && (
          <div className="flex flex-col items-center justify-center py-12 text-center">
            <CheckSquare size={36} className="text-accent-muted mb-3" aria-hidden="true" />
            <p className="text-sm text-ink-muted">No tasks yet</p>
          </div>
        )}
        {CATS.map(cat => {
          const items = todos.filter(t => t.category === cat);
          if (!items.length) return null;
          return (
            <section key={cat} aria-label={`${cat} tasks`}>
              <h3 className="text-sm font-semibold text-ink-secondary mb-2 uppercase tracking-wider">{cat}</h3>
              <div className="space-y-1.5">
                {items.filter(t => t.status !== 'done').sort(byPinned).map(item => (
                  <Row key={item.id} item={item} plan={plan} onToggle={() => toggle(item)} onDel={() => del(item)} onUpd={t => upd(item, t)} onPin={() => pin(item)} onNavigateToDay={navigateToDay} />
                ))}
                {items.filter(t => t.status === 'done').map(item => (
                  <Row key={item.id} item={item} plan={plan} onToggle={() => toggle(item)} onDel={() => del(item)} onUpd={t => upd(item, t)} onPin={() => pin(item)} onNavigateToDay={navigateToDay} />
                ))}
              </div>
            </section>
          );
        })}
      </div>

      {toast && <Toast message={toast.msg} onDismiss={() => setToast(null)} action={toast.undo ? { label: 'Undo', onClick: toast.undo } : undefined} />}
    </div>
  );
}
