import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { render, screen, fireEvent, act } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import { db, type Plan } from '../../../db';
import ActionMenu from '../../ui/ActionMenu';
import { useTripActions, UNDO_MS } from '../useTripActions';
import { duplicateTrip } from '../tripStore';

const plan: Plan = {
  id: 'p1', name: 'Tokyo Explorer', destination: 'Tokyo, Japan', startDate: '2026-10-11', endDate: '2026-10-13',
  createdAt: '', updatedAt: '', deleted: false,
  itinerary: [{ dayIndex: 0, label: 'Day 1', activities: [{ id: 'a1', name: 'Meiji Shrine', time: 'morning', locationName: '', notes: '', pinnedToTodo: false }] }],
};

/** A trip row as the sidebar draws it: the menu, and the actions' messages. */
function Row() {
  const { itemsFor, ui } = useTripActions();
  return (
    <>
      <ActionMenu label="More actions for Tokyo, Japan" menuLabel="Actions" items={itemsFor(plan)} />
      {ui}
    </>
  );
}

const del = async () => {
  fireEvent.click(screen.getByRole('button', { name: 'More actions for Tokyo, Japan' }));
  await act(async () => { fireEvent.click(screen.getByTestId('trip-delete')); });
};

beforeEach(() => {
  vi.clearAllMocks();
  vi.useFakeTimers({ shouldAdvanceTime: true });
});
afterEach(() => vi.useRealTimers());

/*
 * The undo used to belong to the menu, which closed as soon as Delete was
 * chosen: the message never showed, and the trip was gone five seconds later.
 */
describe('deleting a trip', () => {
  it('hides it at once and offers Undo after the menu has closed', async () => {
    render(<MemoryRouter><Row /></MemoryRouter>);
    await del();
    expect(db.plans.update).toHaveBeenCalledWith('p1', expect.objectContaining({ deleted: true }));
    expect(screen.queryByRole('menu')).not.toBeInTheDocument();
    expect(screen.getByText('Deleted Tokyo, Japan')).toBeInTheDocument();
    expect(screen.getByRole('button', { name: 'Undo' })).toBeInTheDocument();
  });

  it('brings it back on Undo, and never purges it', async () => {
    render(<MemoryRouter><Row /></MemoryRouter>);
    await del();
    await act(async () => { fireEvent.click(screen.getByRole('button', { name: 'Undo' })); });
    expect(db.plans.update).toHaveBeenLastCalledWith('p1', expect.objectContaining({ deleted: false }));
    await act(async () => { vi.advanceTimersByTime(UNDO_MS + 100); });
    expect(db.plans.delete).not.toHaveBeenCalled();
  });

  it('removes it for good, with its to-dos and clipboard, once the undo runs out', async () => {
    render(<MemoryRouter><Row /></MemoryRouter>);
    await del();
    await act(async () => { vi.advanceTimersByTime(UNDO_MS + 100); });
    expect(db.plans.delete).toHaveBeenCalledWith('p1');
    expect(db.todos.delete).toHaveBeenCalled();
    expect(db.clipboard.delete).toHaveBeenCalled();
    expect(screen.queryByText('Deleted Tokyo, Japan')).not.toBeInTheDocument();
  });
});

describe('duplicating a trip', () => {
  beforeEach(() => {
    vi.mocked(db.plans.get).mockResolvedValue(plan);
    vi.mocked(db.todos.toArray).mockResolvedValue([
      { id: 't1', planId: 'p1', title: 'Book', category: 'Booking', status: 'todo', autoGenerated: true, sourceActivityId: 'a1', createdAt: '', updatedAt: '' },
    ]);
    vi.mocked(db.clipboard.toArray).mockResolvedValue([]);
  });

  // "(copy)" on the destination sent the map and weather looking for "Tokyo (copy)".
  it('keeps the destination, and names the copy', async () => {
    const id = await duplicateTrip('p1');
    const added = vi.mocked(db.plans.add).mock.calls[0][0] as Plan;
    expect(added.id).toBe(id);
    expect(added.id).not.toBe('p1');
    expect(added.destination).toBe('Tokyo, Japan');
    expect(added.name).toBe('Tokyo Explorer (copy)');
  });

  it('copies the to-dos too, linked to the copy’s own stops', async () => {
    await duplicateTrip('p1');
    const added = vi.mocked(db.plans.add).mock.calls[0][0] as Plan;
    const todos = vi.mocked(db.todos.bulkAdd).mock.calls[0][0] as Array<{ planId: string; sourceActivityId?: string }>;
    expect(todos).toHaveLength(1);
    expect(todos[0].planId).toBe(added.id);
    expect(todos[0].sourceActivityId).toBe(added.itinerary[0].activities[0].id);
  });
});
