import { v4 as uuidv4 } from 'uuid';
import { db, type Plan, type TodoItem } from '../../db';

/**
 * Auto-generate standard to-do items after itinerary generation.
 *
 * Rules (in order):
 *   1. If flights not booked → "Book flights to {destination}" (Booking)
 *   2. If accommodation not booked → "Book accommodation for each night" (Booking)
 *   3. Always → "Apply for visa to {destination}" (Document)
 *      We cannot determine visa requirements client-side; the reminder is
 *      always surfaced as a safe default so the user can dismiss it if not
 *      needed.
 *   4. If kids are travelling → "Check child entry requirements for {destination}" (Document)
 *
 * Deduplication: tasks are keyed by title.  If a task with the same title
 * already exists for this plan, it is silently skipped.  This means calling
 * autoGenerateTodos multiple times (e.g. after itinerary regeneration) is
 * fully safe.
 */
export async function autoGenerateTodos(plan: Plan): Promise<void> {
  const intake = plan.intake;
  if (!intake) return;

  const existing = await db.todos.where('planId').equals(plan.id).toArray();
  const existingTitles = new Set(existing.map((t) => t.title));
  const toAdd: TodoItem[] = [];
  const now = new Date().toISOString();

  const maybeAdd = (item: Omit<TodoItem, 'id' | 'createdAt' | 'updatedAt'>) => {
    if (!existingTitles.has(item.title)) {
      toAdd.push({ ...item, id: uuidv4(), createdAt: now, updatedAt: now });
    }
  };

  // 1. Flights
  if (!intake.flightsBooked) {
    maybeAdd({
      planId: plan.id,
      title: `Book flights to ${plan.destination}`,
      category: 'Booking',
      status: 'todo',
      autoGenerated: true,
    });
  }

  // 2. Accommodation
  if (!intake.accommodationBooked) {
    maybeAdd({
      planId: plan.id,
      title: 'Book accommodation for each night',
      category: 'Booking',
      status: 'todo',
      autoGenerated: true,
    });
  }

  // 3. Visa reminder (always-on — user should verify requirements)
  maybeAdd({
    planId: plan.id,
    title: `Apply for visa to ${plan.destination}`,
    category: 'Document',
    status: 'todo',
    autoGenerated: true,
  });

  // 4. Child entry requirements
  if (intake.kids) {
    maybeAdd({
      planId: plan.id,
      title: `Check child entry requirements for ${plan.destination}`,
      category: 'Document',
      status: 'todo',
      autoGenerated: true,
    });
  }

  if (toAdd.length > 0) {
    await db.todos.bulkAdd(toAdd);
  }
}
