import { v4 as uuidv4 } from 'uuid';
import { db, type Plan, type TodoItem } from '../../db';

export async function autoGenerateTodos(p: Plan): Promise<void> {
  const intake = p.intake;
  if (!intake) return;
  const existing = await db.todos.where('planId').equals(p.id).toArray();
  const existingTitles = new Set(existing.map((t) => t.title));
  const toAdd: TodoItem[] = [];
  const now = new Date().toISOString();

  if (!intake.flightsBooked) {
    const title = `Book flights to ${p.destination}`;
    if (!existingTitles.has(title)) {
      toAdd.push({ id: uuidv4(), planId: p.id, title, category: 'Booking', status: 'todo', autoGenerated: true, createdAt: now, updatedAt: now });
    }
  }
  if (!intake.accommodationBooked) {
    const title = 'Book accommodation for each night';
    if (!existingTitles.has(title)) {
      toAdd.push({ id: uuidv4(), planId: p.id, title, category: 'Booking', status: 'todo', autoGenerated: true, createdAt: now, updatedAt: now });
    }
  }
  if (intake.kids) {
    const title = `Check child entry requirements for ${p.destination}`;
    if (!existingTitles.has(title)) {
      toAdd.push({ id: uuidv4(), planId: p.id, title, category: 'Document', status: 'todo', autoGenerated: true, createdAt: now, updatedAt: now });
    }
  }
  if (toAdd.length > 0) await db.todos.bulkAdd(toAdd);
}
