import { v4 as uuidv4 } from 'uuid';
import { db, type Plan, type TodoItem } from '../../db';

/**
 * Auto-generate standard to-do items after itinerary generation.
 *
 * Rules (in order):
 *   1. If flights not booked → "Book flights to {destination}" (Booking)
 *   2. If accommodation not booked → "Book accommodation for each night" (Booking)
 *   3. Visa, from the intake answer and scoped to the COUNTRY:
 *        needsVisa true  → "Apply for visa to {country}" (Document)
 *        needsVisa null  → "Check visa requirements for {country}" (Document)
 *        needsVisa false → nothing
 *      This used to fire unconditionally against the destination, so a Toronto
 *      trip produced "Apply for visa to Toronto" — wrong twice over: visas are
 *      a country-level rule, and the user may not need one at all.
 *   4. If kids are travelling → "Check child entry requirements for {country}" (Document)
 *
 * Deduplication: tasks are keyed by title.  If a task with the same title
 * already exists for this plan, it is silently skipped.  This means calling
 * autoGenerateTodos multiple times (e.g. after itinerary regeneration) is
 * fully safe.
 */
export async function autoGenerateTodos(plan: Plan): Promise<void> {
  const intake = plan.intake;
  if (!intake) return;

  const existing = await db.todos.where('planId').equals(plan.id).toArray();
  const existingTitles = new Set(existing.map((t) => t.title));
  const toAdd: TodoItem[] = [];
  const now = new Date().toISOString();

  const maybeAdd = (item: Omit<TodoItem, 'id' | 'createdAt' | 'updatedAt'>) => {
    if (!existingTitles.has(item.title)) {
      toAdd.push({ ...item, id: uuidv4(), createdAt: now, updatedAt: now });
    }
  };

  // 1. Flights
  if (!intake.flightsBooked) {
    maybeAdd({
      planId: plan.id,
      title: `Book flights to ${plan.destination}`,
      category: 'Booking',
      status: 'todo',
      autoGenerated: true,
    });
  }

  // 2. Accommodation
  if (!intake.accommodationBooked) {
    maybeAdd({
      planId: plan.id,
      title: 'Book accommodation for each night',
      category: 'Booking',
      status: 'todo',
      autoGenerated: true,
    });
  }

  // Entry rules are set by the country, not the city — "a Toronto visa" is not
  // a thing. Falls back to the destination only when no country was resolved
  // (a free-typed destination with no geocoding match).
  const entryPlace = plan.country ?? plan.destination;

  // 3. Visa — driven by the intake answer rather than assumed.
  if (intake.needsVisa === true) {
    maybeAdd({
      planId: plan.id,
      title: `Apply for visa to ${entryPlace}`,
      category: 'Document',
      status: 'todo',
      autoGenerated: true,
    });
  } else if (intake.needsVisa == null) {
    // Unsure, or never asked (a plan whose intake predates the question):
    // prompt a check rather than an application. `== null` covers both.
    maybeAdd({
      planId: plan.id,
      title: `Check visa requirements for ${entryPlace}`,
      category: 'Document',
      status: 'todo',
      autoGenerated: true,
    });
  }
  // needsVisa === false → nothing, which is the whole point of asking.

  // 4. Child entry requirements — also a country-level rule.
  if (intake.kids) {
    maybeAdd({
      planId: plan.id,
      title: `Check child entry requirements for ${entryPlace}`,
      category: 'Document',
      status: 'todo',
      autoGenerated: true,
    });
  }

  if (toAdd.length > 0) {
    await db.todos.bulkAdd(toAdd);
  }
}
