import { useState } from 'react';
import { ChevronDown, ChevronRight, PlusCircle, Sparkles } from 'lucide-react';
import { v4 as uuidv4 } from 'uuid';
import { type Plan, type Activity, db } from '../../db';
import { getDayColor } from '../../constants/colors';
import Toast from '../ui/Toast';
import GenerateItinerary from './GenerateItinerary';
import ActivityCard from './ActivityCard';
import { scrollBehavior } from '../../utils/motion';
import { sortByTime, swapTimes } from '../../utils/activityTime';
import { findActivityBookings, bookingWarning } from '../../utils/activityBookings';

interface Props { plan: Plan; }

function budgetLabel(
  spend?: { min: number; max: number },
  range?: string | null,
): { text: string; warn: boolean } | null {
  if (!spend) return null;
  const lo = Math.min(spend.min, spend.max);
  const hi = Math.max(spend.min, spend.max);
  const caps: Record<string, number> = { budget: 100, mid: 300, premium: 600 };
  return { text: `Est. $${lo}\u2013${hi}/day`, warn: lo > (caps[range ?? ''] ?? Infinity) };
}

function AddInline({ onAdd }: { onAdd: (n: string, t: string) => Promise<void> }) {
  const [open, setOpen] = useState(false);
  const [nm, setNm] = useState('');
  const [tm, setTm] = useState('09:00');
  if (!open) return (
    <button onClick={() => setOpen(true)} className="flex items-center gap-1 text-xs text-ink-muted hover:text-accent py-1">
      <PlusCircle size={12} /> Add activity
    </button>
  );
  return (
    <form onSubmit={async e => { e.preventDefault(); if (!nm.trim()) return; await onAdd(nm.trim(), tm); setNm(''); setOpen(false); }} className="flex gap-2 items-center">
      <input type="time" value={tm} onChange={e => setTm(e.target.value)} className="bg-surface-raised border border-white/10 rounded-lg px-2 py-1 text-xs text-ink-primary w-24 focus:outline-none" />
      <input autoFocus value={nm} onChange={e => setNm(e.target.value)} placeholder="Activity name"
        className="flex-1 bg-surface-raised border border-white/10 rounded-lg px-2 py-1 text-xs text-ink-primary placeholder:text-ink-muted focus:outline-none" />
      <button type="submit" className="text-xs text-accent hover:underline">Add</button>
      <button type="button" onClick={() => setOpen(false)} className="text-xs text-ink-muted hover:underline">Cancel</button>
    </form>
  );
}

export default function ItineraryView({ plan }: Props) {
  const [collapsed, setCollapsed] = useState<Record<number, boolean>>({});
  const [toast, setToast] = useState<{ msg: string; undo?: () => void } | null>(null);
  const [showGen, setShowGen] = useState(false);

  const persist = (it: typeof plan.itinerary) =>
    db.plans.update(plan.id, { itinerary: it, updatedAt: new Date().toISOString() });

  const delAct = async (di: number, id: string) => {
    const saved = plan.itinerary[di].activities.find(a => a.id === id);
    await persist(plan.itinerary.map((d, i) => i === di ? { ...d, activities: d.activities.filter(a => a.id !== id) } : d));
    setToast({ msg: 'Activity deleted', undo: async () => {
      if (!saved) return;
      await persist(plan.itinerary.map((d, i) => i === di ? { ...d, activities: [...d.activities, saved] } : d));
      setToast(null);
    }});
  };

  const updAct = async (di: number, id: string, u: Partial<Activity>) => {
    // Editing is the other route to a time change, so it needs the same guard
    // as move up/down — otherwise the warning is trivially bypassed.
    const current = plan.itinerary[di]?.activities.find(a => a.id === id);
    if (current && u.time !== undefined && u.time !== current.time) {
      if (!(await confirmTimeChange(current))) return;
    }
    return persist(plan.itinerary.map((d, i) => i === di ? { ...d, activities: d.activities.map(a => a.id === id ? { ...a, ...u } : a) } : d));
  };

  const pinAct = async (di: number, act: Activity) => {
    if (act.pinnedToTodo) {
      const items = await db.todos.where('sourceActivityId').equals(act.id).toArray();
      if (items.length && !window.confirm('Remove from To-Do?')) return;
      await db.todos.bulkDelete(items.map(t => t.id));
      await updAct(di, act.id, { pinnedToTodo: false });
    } else {
      await db.todos.add({ id: uuidv4(), planId: plan.id, title: act.name, category: 'Other', status: 'todo', autoGenerated: false, sourceActivityId: act.id, sourceDayIndex: di, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() });
      await updAct(di, act.id, { pinnedToTodo: true });
      setToast({ msg: `"${act.name}" pinned to To-Do` });
    }
  };

  /**
   * Move up / down trades times with the neighbour.
   *
   * Splicing the array would achieve nothing: the day is sorted by time on
   * render, so the sort would immediately put the card back. Swapping keeps
   * the exact times the user typed rather than inventing one between two
   * neighbours, which is what dropping a dragged card into a gap would need.
   */
  const moveAct = async (di: number, idx: number, dir: 'up' | 'down') => {
    const acts = sortByTime(plan.itinerary[di].activities);
    const ni = dir === 'up' ? idx - 1 : idx + 1;
    if (ni < 0 || ni >= acts.length) return;

    const moving = acts[idx];
    const other = acts[ni];
    if (!(await confirmTimeChange(moving))) return;

    const swapped = swapTimes(plan.itinerary[di].activities, moving.id, other.id);
    await persist(plan.itinerary.map((d, i) => (i === di ? { ...d, activities: swapped } : d)));
  };

  /**
   * A booked activity is one the user has already committed to — a linked
   * clipboard confirmation, or a to-do they ticked off. Changing its time may
   * not match what was booked, so name what is at stake and let them decide.
   */
  const confirmTimeChange = async (act: Activity): Promise<boolean> => {
    const bookings = await findActivityBookings(plan.id, act.id);
    if (!bookings.length) return true;
    return window.confirm(`${bookingWarning(bookings)}

Change it anyway?`);
  };

  if (showGen || !plan.itinerary?.length)
    return <GenerateItinerary plan={plan} onGenerated={() => setShowGen(false)} />;

  return (
    <div className="flex flex-col h-full" data-testid="itinerary-view">
      <div className="px-4 py-2 border-b border-white/5 flex items-center gap-2 overflow-x-auto shrink-0">
        {plan.itinerary.map(d => (
          <button key={d.dayIndex}
            onClick={() => document.getElementById(`day-${d.dayIndex}`)?.scrollIntoView({ behavior: scrollBehavior() })}
            className="shrink-0 text-xs px-3 py-1 rounded-full border border-white/10 text-ink-secondary hover:text-ink-primary transition-colors">
            {d.label.split(' \u2014 ')[0]}
          </button>
        ))}
        <button onClick={() => setShowGen(true)} className="shrink-0 flex items-center gap-1 text-xs px-3 py-1 rounded-full border border-white/10 text-accent hover:bg-accent/10 ml-auto">
          <Sparkles size={12} /> Regenerate
        </button>
      </div>

      <div className="flex-1 min-h-0 overflow-y-auto px-4 py-4 space-y-4" data-testid="itinerary-days">
        {plan.itinerary.map(day => {
          const isCol = collapsed[day.dayIndex];
          const bb = budgetLabel(day.estimatedDailySpend, plan.intake?.budgetRange);

          return (
            <section key={day.dayIndex} id={`day-${day.dayIndex}`}
              aria-label={day.label}>
              <button
                className="w-full flex items-center gap-2 py-2 text-left"
                onClick={() => setCollapsed(p => ({ ...p, [day.dayIndex]: !p[day.dayIndex] }))}
                aria-expanded={!isCol}>
                <span className="w-2 h-2 rounded-full shrink-0" style={{ backgroundColor: getDayColor(day.dayIndex) }} aria-hidden="true" />
                <span className="text-base font-semibold text-ink-primary flex-1">{day.label}</span>
                {bb && <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${bb.warn ? 'text-status-warning bg-status-warning/10' : 'text-accent bg-accent/10'}`}>{bb.text}</span>}
                {isCol ? <ChevronRight size={16} className="text-ink-muted" /> : <ChevronDown size={16} className="text-ink-muted" />}
              </button>

              {!isCol && (
                <div className={`space-y-2 ml-4 border-l-2 pl-3 pb-2 border-white/5`}>
                  {day.activities.length === 0 && <p className="text-xs text-ink-muted py-2">No activities yet.</p>}
                  {sortByTime(day.activities).map((act, ai) => (
                    <div key={act.id}>
                      <ActivityCard act={act} plan={plan}
                        onDel={() => delAct(day.dayIndex, act.id)}
                        onUpd={u => updAct(day.dayIndex, act.id, u)}
                        onPin={() => pinAct(day.dayIndex, act)} />
                      {/* The only way to reorder on touch — HTML5 drag and drop
                          does not fire on mobile — so these get real tap
                          targets rather than the 16px-tall text links they
                          were, which were effectively unhittable on a phone. */}
                      <div className="flex gap-1 mt-0.5 pl-6">
                        <button disabled={ai === 0} onClick={() => moveAct(day.dayIndex, ai, 'up')} className="text-xs text-ink-muted hover:text-ink-primary disabled:opacity-30 px-2 py-2 md:py-0.5 rounded-lg" aria-label={`Move ${act.name} up`}>&#8593; Move up</button>
                        <button disabled={ai === day.activities.length - 1} onClick={() => moveAct(day.dayIndex, ai, 'down')} className="text-xs text-ink-muted hover:text-ink-primary disabled:opacity-30 px-2 py-2 md:py-0.5 rounded-lg" aria-label={`Move ${act.name} down`}>&#8595; Move down</button>
                      </div>
                    </div>
                  ))}
                  <AddInline onAdd={async (name, time) => {
                    const newAct: Activity = { id: uuidv4(), name, time, locationName: '', notes: '', pinnedToTodo: false };
                    await persist(plan.itinerary.map((d, i) => i === day.dayIndex ? { ...d, activities: [...d.activities, newAct] } : d));
                  }} />
                </div>
              )}
            </section>
          );
        })}
      </div>

      {toast && <Toast message={toast.msg} onDismiss={() => setToast(null)} action={toast.undo ? { label: 'Undo', onClick: toast.undo } : undefined} />}
    </div>
  );
}
