import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import TodoList from '../TodoList';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../../../db';

vi.mock('dexie-react-hooks');

const mockTodos = [
  {
    id: 'todo-1',
    planId: 'plan-1',
    title: 'Book flights to Tokyo',
    category: 'Booking',
    status: 'todo',
    autoGenerated: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'todo-2',
    planId: 'plan-1',
    title: 'Pack rain jacket',
    category: 'Packing',
    status: 'done',
    autoGenerated: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

describe('TodoList', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('renders tasks grouped by category', () => {
    vi.mocked(useLiveQuery).mockReturnValue(mockTodos);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByText('Book flights to Tokyo')).toBeInTheDocument();
    expect(screen.getByText('Pack rain jacket')).toBeInTheDocument();
  });

  it('shows progress bar when tasks exist', () => {
    vi.mocked(useLiveQuery).mockReturnValue(mockTodos);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByRole('progressbar')).toBeInTheDocument();
    expect(screen.getByText('1 of 2 complete')).toBeInTheDocument();
  });

  it('hides progress bar when no tasks', () => {
    vi.mocked(useLiveQuery).mockReturnValue([]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.queryByRole('progressbar')).not.toBeInTheDocument();
  });

  it('shows celebration when all done', () => {
    const allDone = mockTodos.map((t) => ({ ...t, status: 'done' }));
    vi.mocked(useLiveQuery).mockReturnValue(allDone);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByText('✓ All done!')).toBeInTheDocument();
  });

  it('shows add form when clicking Add task', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    fireEvent.click(screen.getByTestId('add-task-btn'));
    await waitFor(() => {
      expect(screen.getByTestId('add-task-form')).toBeInTheDocument();
    });
  });

  it('validates blank title on save', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    fireEvent.click(screen.getByTestId('add-task-btn'));
    fireEvent.click(screen.getByTestId('save-task-btn'));
    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('Title is required');
    });
  });

  it('saves a new task on valid submission', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([]);
    vi.mocked(db.todos.add).mockResolvedValue('new-id');
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    fireEvent.click(screen.getByTestId('add-task-btn'));
    fireEvent.change(screen.getByTestId('task-title-input'), {
      target: { value: 'Get travel insurance' },
    });
    fireEvent.click(screen.getByTestId('save-task-btn'));
    await waitFor(() => {
      expect(db.todos.add).toHaveBeenCalledWith(
        expect.objectContaining({ title: 'Get travel insurance', planId: 'plan-1' }),
      );
    });
  });

  it('shows Generated badge on auto-generated tasks', () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[0]]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByText('Generated')).toBeInTheDocument();
  });

  it('shows loading spinner when todos undefined', () => {
    vi.mocked(useLiveQuery).mockReturnValue(undefined);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByLabelText('Loading')).toBeInTheDocument();
  });
});
