import { describe, it, expect, vi, beforeEach } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { MemoryRouter } from 'react-router-dom';
import TodoList from '../TodoList';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../../../db';

vi.mock('dexie-react-hooks');

const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];

const mockTodos = [
  {
    id: 'todo-1',
    planId: 'plan-1',
    title: 'Book flights to Tokyo',
    category: 'Booking',
    status: 'todo',
    autoGenerated: true,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'todo-2',
    planId: 'plan-1',
    title: 'Pack rain jacket',
    category: 'Packing',
    status: 'done',
    autoGenerated: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const mockPinnedTodo = {
  id: 'todo-3',
  planId: 'plan-1',
  title: 'Tsukiji Market',
  category: 'Other',
  status: 'todo' as const,
  autoGenerated: false,
  sourceActivityId: 'act-1',
  sourceDayIndex: 0,
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
};

describe('TodoList', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // ── Add/Edit/Delete (Flow 10, Story 1) ──────────────────────────────────

  it('renders tasks grouped by category', () => {
    vi.mocked(useLiveQuery).mockReturnValue(mockTodos);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByText('Book flights to Tokyo')).toBeInTheDocument();
    expect(screen.getByText('Pack rain jacket')).toBeInTheDocument();
  });

  it('renders category section headers', () => {
    vi.mocked(useLiveQuery).mockReturnValue(mockTodos);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByRole('region', { name: /booking tasks/i })).toBeInTheDocument();
    expect(screen.getByRole('region', { name: /packing tasks/i })).toBeInTheDocument();
  });

  it('shows add form when clicking Add task', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    fireEvent.click(screen.getByTestId('add-task-btn'));
    await waitFor(() => {
      expect(screen.getByTestId('add-task-form')).toBeInTheDocument();
    });
  });

  it('validates blank title on save', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    fireEvent.click(screen.getByTestId('add-task-btn'));
    fireEvent.click(screen.getByTestId('save-task-btn'));
    await waitFor(() => {
      expect(screen.getByRole('alert')).toHaveTextContent('Title is required');
    });
  });

  it('saves a new task on valid submission', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([]);
    vi.mocked(db.todos.add).mockResolvedValue('new-id');
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    fireEvent.click(screen.getByTestId('add-task-btn'));
    fireEvent.change(screen.getByTestId('task-title-input'), {
      target: { value: 'Get travel insurance' },
    });
    fireEvent.click(screen.getByTestId('save-task-btn'));
    await waitFor(() => {
      expect(db.todos.add).toHaveBeenCalledWith(
        expect.objectContaining({ title: 'Get travel insurance', planId: 'plan-1' }),
      );
    });
  });

  it('inline edit: clicking title makes it editable', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[0]]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    // The title is a button — clicking it should switch to edit mode
    const titleBtn = screen.getByText('Book flights to Tokyo');
    fireEvent.click(titleBtn);
    await waitFor(() => {
      expect(screen.getByLabelText('Edit title')).toBeInTheDocument();
    });
  });

  /*
   * Saving on blur meant the only way to find out whether an edit had taken
   * was to look. The editor now ends in a Save, the way the itinerary and
   * clipboard editors do.
   */
  it('inline edit: saving updated title calls db.todos.update', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[0]]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    const titleBtn = screen.getByText('Book flights to Tokyo');
    fireEvent.click(titleBtn);
    const editInput = await screen.findByLabelText('Edit title');
    fireEvent.change(editInput, { target: { value: 'Book flights to Osaka' } });
    fireEvent.click(screen.getByTestId('task-save-btn'));
    await waitFor(() => {
      expect(db.todos.update).toHaveBeenCalledWith(
        'todo-1',
        expect.objectContaining({ title: 'Book flights to Osaka' }),
      );
    });
  });

  it('delete: shows undo toast after deleting a task', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[0]]);
    vi.mocked(db.todos.delete).mockResolvedValue(undefined);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    const delBtn = screen.getByLabelText(/delete: book flights/i);
    fireEvent.click(delBtn);
    await waitFor(() => {
      expect(db.todos.delete).toHaveBeenCalledWith('todo-1');
      expect(screen.getByText('Task deleted')).toBeInTheDocument();
    });
  });

  it('delete: undo restores the task via db.todos.add', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[0]]);
    vi.mocked(db.todos.delete).mockResolvedValue(undefined);
    vi.mocked(db.todos.add).mockResolvedValue('todo-1');
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    const delBtn = screen.getByLabelText(/delete: book flights/i);
    fireEvent.click(delBtn);
    const undoBtn = await screen.findByText('Undo');
    fireEvent.click(undoBtn);
    await waitFor(() => {
      expect(db.todos.add).toHaveBeenCalledWith(
        expect.objectContaining({ id: 'todo-1', title: 'Book flights to Tokyo' }),
      );
    });
  });

  it('shows past-due date with warning colour class', () => {
    const pastTodo = { ...mockTodos[0], dueDate: yesterday };
    vi.mocked(useLiveQuery).mockReturnValue([pastTodo]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    // The "Past" label should appear next to the date input in the form area
    // In the task row, the due date span should carry warning styling
    expect(screen.getByText(`Due ${yesterday}`)).toBeInTheDocument();
  });

  it('shows loading spinner when todos undefined', () => {
    vi.mocked(useLiveQuery).mockReturnValue(undefined);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByLabelText('Loading')).toBeInTheDocument();
  });

  // ── Progress / Complete (Flow 10, Story 2) ──────────────────────────────

  it('shows progress bar when tasks exist', () => {
    vi.mocked(useLiveQuery).mockReturnValue(mockTodos);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByRole('progressbar')).toBeInTheDocument();
    expect(screen.getByText('1 of 2 complete')).toBeInTheDocument();
  });

  it('hides progress bar when no tasks', () => {
    vi.mocked(useLiveQuery).mockReturnValue([]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.queryByRole('progressbar')).not.toBeInTheDocument();
  });

  it('shows celebration when all done', () => {
    const allDone = mockTodos.map((t) => ({ ...t, status: 'done' }));
    vi.mocked(useLiveQuery).mockReturnValue(allDone);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByText('✓ All done!')).toBeInTheDocument();
  });

  it('toggles task status on checkbox click', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[0]]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    const checkbox = screen.getByLabelText('Mark complete');
    fireEvent.click(checkbox);
    await waitFor(() => {
      expect(db.todos.update).toHaveBeenCalledWith(
        'todo-1',
        expect.objectContaining({ status: 'done' }),
      );
    });
  });

  it('toggles a done task back to todo on checkbox click', async () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[1]]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    const checkbox = screen.getByLabelText('Mark incomplete');
    fireEvent.click(checkbox);
    await waitFor(() => {
      expect(db.todos.update).toHaveBeenCalledWith(
        'todo-2',
        expect.objectContaining({ status: 'todo' }),
      );
    });
  });

  it('completed tasks appear with line-through text', () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[1]]); // status: done
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    const titleBtn = screen.getByText('Pack rain jacket');
    expect(titleBtn.className).toContain('line-through');
  });

  // ── Generated badge ──────────────────────────────────────────────────────

  it('shows Generated badge on auto-generated tasks', () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockTodos[0]]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByText('Generated')).toBeInTheDocument();
  });

  // ── Pin from itinerary (Flow 11) ─────────────────────────────────────────

  it('shows From itinerary badge on pinned tasks with day label', () => {
    vi.mocked(useLiveQuery).mockReturnValue([mockPinnedTodo]);
    render(<MemoryRouter><TodoList planId="plan-1" /></MemoryRouter>);
    expect(screen.getByText(/From itinerary.*Day 1/)).toBeInTheDocument();
  });
});
